// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: custom_domains.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countCustomDomainsByStoreID = `-- name: CountCustomDomainsByStoreID :one
SELECT COUNT(*) FROM custom_domains
WHERE store_id = $1
`

func (q *Queries) CountCustomDomainsByStoreID(ctx context.Context, storeID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCustomDomainsByStoreID, storeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomDomain = `-- name: CreateCustomDomain :one

INSERT INTO custom_domains (gid, domain, store_id, tenant_id, verification_token)
VALUES ($1, $2, $3, $4, '')
RETURNING id, gid, domain, store_id, tenant_id, verification_status, verification_token, verified_at, ssl_status, ssl_expires_at, is_primary, created_at, updated_at
`

type CreateCustomDomainParams struct {
	Gid      int64
	Domain   string
	StoreID  uuid.UUID
	TenantID uuid.UUID
}

// Custom Domain Management
func (q *Queries) CreateCustomDomain(ctx context.Context, arg CreateCustomDomainParams) (CustomDomain, error) {
	row := q.db.QueryRowContext(ctx, createCustomDomain,
		arg.Gid,
		arg.Domain,
		arg.StoreID,
		arg.TenantID,
	)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.Gid,
		&i.Domain,
		&i.StoreID,
		&i.TenantID,
		&i.VerificationStatus,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.SslExpiresAt,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomDomain = `-- name: DeleteCustomDomain :exec
DELETE FROM custom_domains
WHERE id = $1 AND store_id = $2
`

type DeleteCustomDomainParams struct {
	ID      uuid.UUID
	StoreID uuid.UUID
}

func (q *Queries) DeleteCustomDomain(ctx context.Context, arg DeleteCustomDomainParams) error {
	_, err := q.db.ExecContext(ctx, deleteCustomDomain, arg.ID, arg.StoreID)
	return err
}

const getCustomDomainByDomain = `-- name: GetCustomDomainByDomain :one
SELECT id, gid, domain, store_id, tenant_id, verification_status, verification_token, verified_at, ssl_status, ssl_expires_at, is_primary, created_at, updated_at FROM custom_domains
WHERE domain = $1
`

func (q *Queries) GetCustomDomainByDomain(ctx context.Context, domain string) (CustomDomain, error) {
	row := q.db.QueryRowContext(ctx, getCustomDomainByDomain, domain)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.Gid,
		&i.Domain,
		&i.StoreID,
		&i.TenantID,
		&i.VerificationStatus,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.SslExpiresAt,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomDomainByGID = `-- name: GetCustomDomainByGID :one
SELECT id, gid, domain, store_id, tenant_id, verification_status, verification_token, verified_at, ssl_status, ssl_expires_at, is_primary, created_at, updated_at FROM custom_domains
WHERE gid = $1
`

func (q *Queries) GetCustomDomainByGID(ctx context.Context, gid int64) (CustomDomain, error) {
	row := q.db.QueryRowContext(ctx, getCustomDomainByGID, gid)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.Gid,
		&i.Domain,
		&i.StoreID,
		&i.TenantID,
		&i.VerificationStatus,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.SslExpiresAt,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomDomainByID = `-- name: GetCustomDomainByID :one
SELECT id, gid, domain, store_id, tenant_id, verification_status, verification_token, verified_at, ssl_status, ssl_expires_at, is_primary, created_at, updated_at FROM custom_domains
WHERE id = $1
`

func (q *Queries) GetCustomDomainByID(ctx context.Context, id uuid.UUID) (CustomDomain, error) {
	row := q.db.QueryRowContext(ctx, getCustomDomainByID, id)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.Gid,
		&i.Domain,
		&i.StoreID,
		&i.TenantID,
		&i.VerificationStatus,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.SslExpiresAt,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomDomainsByStoreID = `-- name: GetCustomDomainsByStoreID :many
SELECT id, gid, domain, store_id, tenant_id, verification_status, verification_token, verified_at, ssl_status, ssl_expires_at, is_primary, created_at, updated_at FROM custom_domains
WHERE store_id = $1
ORDER BY is_primary DESC, created_at ASC
`

func (q *Queries) GetCustomDomainsByStoreID(ctx context.Context, storeID uuid.UUID) ([]CustomDomain, error) {
	rows, err := q.db.QueryContext(ctx, getCustomDomainsByStoreID, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomDomain
	for rows.Next() {
		var i CustomDomain
		if err := rows.Scan(
			&i.ID,
			&i.Gid,
			&i.Domain,
			&i.StoreID,
			&i.TenantID,
			&i.VerificationStatus,
			&i.VerificationToken,
			&i.VerifiedAt,
			&i.SslStatus,
			&i.SslExpiresAt,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomDomainsByTenantID = `-- name: GetCustomDomainsByTenantID :many
SELECT id, gid, domain, store_id, tenant_id, verification_status, verification_token, verified_at, ssl_status, ssl_expires_at, is_primary, created_at, updated_at FROM custom_domains
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCustomDomainsByTenantID(ctx context.Context, tenantID uuid.UUID) ([]CustomDomain, error) {
	rows, err := q.db.QueryContext(ctx, getCustomDomainsByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomDomain
	for rows.Next() {
		var i CustomDomain
		if err := rows.Scan(
			&i.ID,
			&i.Gid,
			&i.Domain,
			&i.StoreID,
			&i.TenantID,
			&i.VerificationStatus,
			&i.VerificationToken,
			&i.VerifiedAt,
			&i.SslStatus,
			&i.SslExpiresAt,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingDomainVerifications = `-- name: GetPendingDomainVerifications :many
SELECT id, gid, domain, store_id, tenant_id, verification_status, verification_token, verified_at, ssl_status, ssl_expires_at, is_primary, created_at, updated_at FROM custom_domains
WHERE verification_status = 'pending'
  AND created_at > now() - INTERVAL '7 days'
ORDER BY created_at ASC
`

func (q *Queries) GetPendingDomainVerifications(ctx context.Context) ([]CustomDomain, error) {
	rows, err := q.db.QueryContext(ctx, getPendingDomainVerifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomDomain
	for rows.Next() {
		var i CustomDomain
		if err := rows.Scan(
			&i.ID,
			&i.Gid,
			&i.Domain,
			&i.StoreID,
			&i.TenantID,
			&i.VerificationStatus,
			&i.VerificationToken,
			&i.VerifiedAt,
			&i.SslStatus,
			&i.SslExpiresAt,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreByCustomDomain = `-- name: GetStoreByCustomDomain :one
SELECT s.id, s.name, s.handle, s.address, s.status, s.default_currency, s.timezone, s.plan, s.created_at, s.updated_at, s.tenant_id, s.gid FROM stores s
JOIN custom_domains cd ON s.id = cd.store_id
WHERE cd.domain = $1
  AND cd.verification_status = 'verified'
`

func (q *Queries) GetStoreByCustomDomain(ctx context.Context, domain string) (Store, error) {
	row := q.db.QueryRowContext(ctx, getStoreByCustomDomain, domain)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Address,
		&i.Status,
		&i.DefaultCurrency,
		&i.Timezone,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.Gid,
	)
	return i, err
}

const getVerifiedCustomDomainByDomain = `-- name: GetVerifiedCustomDomainByDomain :one
SELECT id, gid, domain, store_id, tenant_id, verification_status, verification_token, verified_at, ssl_status, ssl_expires_at, is_primary, created_at, updated_at FROM custom_domains
WHERE domain = $1 AND verification_status = 'verified'
`

func (q *Queries) GetVerifiedCustomDomainByDomain(ctx context.Context, domain string) (CustomDomain, error) {
	row := q.db.QueryRowContext(ctx, getVerifiedCustomDomainByDomain, domain)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.Gid,
		&i.Domain,
		&i.StoreID,
		&i.TenantID,
		&i.VerificationStatus,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.SslExpiresAt,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPrimaryDomain = `-- name: SetPrimaryDomain :exec
UPDATE custom_domains
SET is_primary = (id = $2), updated_at = now()
WHERE store_id = $1
`

type SetPrimaryDomainParams struct {
	StoreID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) SetPrimaryDomain(ctx context.Context, arg SetPrimaryDomainParams) error {
	_, err := q.db.ExecContext(ctx, setPrimaryDomain, arg.StoreID, arg.ID)
	return err
}

const updateCustomDomainSSLStatus = `-- name: UpdateCustomDomainSSLStatus :one
UPDATE custom_domains
SET
    ssl_status = $2,
    ssl_expires_at = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, gid, domain, store_id, tenant_id, verification_status, verification_token, verified_at, ssl_status, ssl_expires_at, is_primary, created_at, updated_at
`

type UpdateCustomDomainSSLStatusParams struct {
	ID           uuid.UUID
	SslStatus    string
	SslExpiresAt sql.NullTime
}

func (q *Queries) UpdateCustomDomainSSLStatus(ctx context.Context, arg UpdateCustomDomainSSLStatusParams) (CustomDomain, error) {
	row := q.db.QueryRowContext(ctx, updateCustomDomainSSLStatus, arg.ID, arg.SslStatus, arg.SslExpiresAt)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.Gid,
		&i.Domain,
		&i.StoreID,
		&i.TenantID,
		&i.VerificationStatus,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.SslExpiresAt,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomDomainVerificationStatus = `-- name: UpdateCustomDomainVerificationStatus :one
UPDATE custom_domains
SET
    verification_status = $2,
    verified_at = CASE WHEN $2 = 'verified' THEN now() ELSE verified_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, gid, domain, store_id, tenant_id, verification_status, verification_token, verified_at, ssl_status, ssl_expires_at, is_primary, created_at, updated_at
`

type UpdateCustomDomainVerificationStatusParams struct {
	ID                 uuid.UUID
	VerificationStatus string
}

func (q *Queries) UpdateCustomDomainVerificationStatus(ctx context.Context, arg UpdateCustomDomainVerificationStatusParams) (CustomDomain, error) {
	row := q.db.QueryRowContext(ctx, updateCustomDomainVerificationStatus, arg.ID, arg.VerificationStatus)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.Gid,
		&i.Domain,
		&i.StoreID,
		&i.TenantID,
		&i.VerificationStatus,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.SslExpiresAt,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
