// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Product struct {
	ID               uuid.UUID
	StoreID          uuid.UUID
	Handle           string
	Name             string
	Description      sql.NullString
	InventoryTracked bool
	Sku              sql.NullString
	Tags             sql.NullString
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Store struct {
	ID              uuid.UUID
	Name            string
	Handle          string
	Address         string
	Status          string
	DefaultCurrency string
	Timezone        string
	Plan            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type StoreMembership struct {
	ID        uuid.UUID
	StoreID   uuid.UUID
	UserID    uuid.UUID
	Role      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Email          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
}
