// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Permission struct {
	ID          uuid.UUID
	Key         string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Product struct {
	ID               uuid.UUID
	StoreID          uuid.UUID
	Handle           string
	Name             string
	Description      sql.NullString
	InventoryTracked bool
	Sku              sql.NullString
	Tags             sql.NullString
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ProductVariant struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	StoreID        uuid.UUID
	ProductID      uuid.UUID
	Sku            sql.NullString
	Barcode        sql.NullString
	Title          string
	PriceCents     int32
	CompareAtCents sql.NullInt32
	OptionValues   json.RawMessage
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Role struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RolePermission struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type Store struct {
	ID              uuid.UUID
	Name            string
	Handle          string
	Address         string
	Status          string
	DefaultCurrency string
	Timezone        string
	Plan            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	TenantID        uuid.NullUUID
}

type StoreMembership struct {
	ID        uuid.UUID
	StoreID   uuid.UUID
	UserID    uuid.UUID
	Role      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Tenant struct {
	ID        uuid.UUID
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TenantUser struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TenantUserRole struct {
	TenantUserID uuid.UUID
	RoleID       uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Email          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
}
