// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product_variants.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countProductVariantsByProductID = `-- name: CountProductVariantsByProductID :one
SELECT COUNT(*) FROM product_variants
WHERE product_id = $1
`

func (q *Queries) CountProductVariantsByProductID(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductVariantsByProductID, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variants (
    id, tenant_id, store_id, product_id, sku, barcode, title,
    price_cents, compare_at_cents, option_values, status, created_at, updated_at
)
VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now(), now()
)
RETURNING id, tenant_id, store_id, product_id, sku, barcode, title, price_cents, compare_at_cents, option_values, status, created_at, updated_at
`

type CreateProductVariantParams struct {
	TenantID       uuid.UUID
	StoreID        uuid.UUID
	ProductID      uuid.UUID
	Sku            sql.NullString
	Barcode        sql.NullString
	Title          string
	PriceCents     int32
	CompareAtCents sql.NullInt32
	OptionValues   json.RawMessage
	Status         string
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, createProductVariant,
		arg.TenantID,
		arg.StoreID,
		arg.ProductID,
		arg.Sku,
		arg.Barcode,
		arg.Title,
		arg.PriceCents,
		arg.CompareAtCents,
		arg.OptionValues,
		arg.Status,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StoreID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Title,
		&i.PriceCents,
		&i.CompareAtCents,
		&i.OptionValues,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductVariant = `-- name: DeleteProductVariant :exec
DELETE FROM product_variants
WHERE id = $1 AND product_id = $2
`

type DeleteProductVariantParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) DeleteProductVariant(ctx context.Context, arg DeleteProductVariantParams) error {
	_, err := q.db.ExecContext(ctx, deleteProductVariant, arg.ID, arg.ProductID)
	return err
}

const deleteProductVariantsByProductID = `-- name: DeleteProductVariantsByProductID :exec
DELETE FROM product_variants
WHERE product_id = $1
`

func (q *Queries) DeleteProductVariantsByProductID(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductVariantsByProductID, productID)
	return err
}

const getProductVariantByBarcode = `-- name: GetProductVariantByBarcode :one
SELECT id, tenant_id, store_id, product_id, sku, barcode, title, price_cents, compare_at_cents, option_values, status, created_at, updated_at FROM product_variants
WHERE store_id = $1 AND barcode = $2
`

type GetProductVariantByBarcodeParams struct {
	StoreID uuid.UUID
	Barcode sql.NullString
}

func (q *Queries) GetProductVariantByBarcode(ctx context.Context, arg GetProductVariantByBarcodeParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, getProductVariantByBarcode, arg.StoreID, arg.Barcode)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StoreID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Title,
		&i.PriceCents,
		&i.CompareAtCents,
		&i.OptionValues,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductVariantByID = `-- name: GetProductVariantByID :one
SELECT id, tenant_id, store_id, product_id, sku, barcode, title, price_cents, compare_at_cents, option_values, status, created_at, updated_at FROM product_variants
WHERE id = $1
`

func (q *Queries) GetProductVariantByID(ctx context.Context, id uuid.UUID) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, getProductVariantByID, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StoreID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Title,
		&i.PriceCents,
		&i.CompareAtCents,
		&i.OptionValues,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductVariantBySKU = `-- name: GetProductVariantBySKU :one
SELECT id, tenant_id, store_id, product_id, sku, barcode, title, price_cents, compare_at_cents, option_values, status, created_at, updated_at FROM product_variants
WHERE store_id = $1 AND sku = $2
`

type GetProductVariantBySKUParams struct {
	StoreID uuid.UUID
	Sku     sql.NullString
}

func (q *Queries) GetProductVariantBySKU(ctx context.Context, arg GetProductVariantBySKUParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, getProductVariantBySKU, arg.StoreID, arg.Sku)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StoreID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Title,
		&i.PriceCents,
		&i.CompareAtCents,
		&i.OptionValues,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductVariantsByProductID = `-- name: GetProductVariantsByProductID :many
SELECT id, tenant_id, store_id, product_id, sku, barcode, title, price_cents, compare_at_cents, option_values, status, created_at, updated_at FROM product_variants
WHERE product_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetProductVariantsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductVariant, error) {
	rows, err := q.db.QueryContext(ctx, getProductVariantsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StoreID,
			&i.ProductID,
			&i.Sku,
			&i.Barcode,
			&i.Title,
			&i.PriceCents,
			&i.CompareAtCents,
			&i.OptionValues,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductVariantsByProductIDPaginated = `-- name: GetProductVariantsByProductIDPaginated :many
SELECT id, tenant_id, store_id, product_id, sku, barcode, title,
       price_cents, compare_at_cents, option_values, status, created_at, updated_at
FROM product_variants
WHERE product_id = $1
  AND (
    $2::boolean = false
    OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type GetProductVariantsByProductIDPaginatedParams struct {
	ProductID uuid.UUID
	Column2   bool
	Column3   time.Time
	Column4   uuid.UUID
	Limit     int32
}

func (q *Queries) GetProductVariantsByProductIDPaginated(ctx context.Context, arg GetProductVariantsByProductIDPaginatedParams) ([]ProductVariant, error) {
	rows, err := q.db.QueryContext(ctx, getProductVariantsByProductIDPaginated,
		arg.ProductID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StoreID,
			&i.ProductID,
			&i.Sku,
			&i.Barcode,
			&i.Title,
			&i.PriceCents,
			&i.CompareAtCents,
			&i.OptionValues,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductVariantsByStoreID = `-- name: GetProductVariantsByStoreID :many
SELECT id, tenant_id, store_id, product_id, sku, barcode, title, price_cents, compare_at_cents, option_values, status, created_at, updated_at FROM product_variants
WHERE store_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetProductVariantsByStoreID(ctx context.Context, storeID uuid.UUID) ([]ProductVariant, error) {
	rows, err := q.db.QueryContext(ctx, getProductVariantsByStoreID, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StoreID,
			&i.ProductID,
			&i.Sku,
			&i.Barcode,
			&i.Title,
			&i.PriceCents,
			&i.CompareAtCents,
			&i.OptionValues,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductWithVariants = `-- name: GetProductWithVariants :many
SELECT
    p.id as product_id,
    p.store_id,
    p.handle,
    p.name as product_name,
    p.description,
    p.inventory_tracked,
    p.sku as product_sku,
    p.tags,
    p.status as product_status,
    p.created_at as product_created_at,
    p.updated_at as product_updated_at,
    pv.id as variant_id,
    pv.tenant_id,
    pv.sku as variant_sku,
    pv.barcode,
    pv.title as variant_title,
    pv.price_cents,
    pv.compare_at_cents,
    pv.option_values,
    pv.status as variant_status,
    pv.created_at as variant_created_at,
    pv.updated_at as variant_updated_at
FROM products p
LEFT JOIN product_variants pv ON p.id = pv.product_id
WHERE p.id = $1 AND p.store_id = $2
`

type GetProductWithVariantsParams struct {
	ID      uuid.UUID
	StoreID uuid.UUID
}

type GetProductWithVariantsRow struct {
	ProductID        uuid.UUID
	StoreID          uuid.UUID
	Handle           string
	ProductName      string
	Description      sql.NullString
	InventoryTracked bool
	ProductSku       sql.NullString
	Tags             sql.NullString
	ProductStatus    string
	ProductCreatedAt time.Time
	ProductUpdatedAt time.Time
	VariantID        uuid.NullUUID
	TenantID         uuid.NullUUID
	VariantSku       sql.NullString
	Barcode          sql.NullString
	VariantTitle     sql.NullString
	PriceCents       sql.NullInt32
	CompareAtCents   sql.NullInt32
	OptionValues     pqtype.NullRawMessage
	VariantStatus    sql.NullString
	VariantCreatedAt sql.NullTime
	VariantUpdatedAt sql.NullTime
}

func (q *Queries) GetProductWithVariants(ctx context.Context, arg GetProductWithVariantsParams) ([]GetProductWithVariantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductWithVariants, arg.ID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductWithVariantsRow
	for rows.Next() {
		var i GetProductWithVariantsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.StoreID,
			&i.Handle,
			&i.ProductName,
			&i.Description,
			&i.InventoryTracked,
			&i.ProductSku,
			&i.Tags,
			&i.ProductStatus,
			&i.ProductCreatedAt,
			&i.ProductUpdatedAt,
			&i.VariantID,
			&i.TenantID,
			&i.VariantSku,
			&i.Barcode,
			&i.VariantTitle,
			&i.PriceCents,
			&i.CompareAtCents,
			&i.OptionValues,
			&i.VariantStatus,
			&i.VariantCreatedAt,
			&i.VariantUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductVariant = `-- name: UpdateProductVariant :one
UPDATE product_variants
SET
    sku = $3,
    barcode = $4,
    title = $5,
    price_cents = $6,
    compare_at_cents = $7,
    option_values = $8,
    status = $9,
    updated_at = now()
WHERE id = $1 AND product_id = $2
RETURNING id, tenant_id, store_id, product_id, sku, barcode, title, price_cents, compare_at_cents, option_values, status, created_at, updated_at
`

type UpdateProductVariantParams struct {
	ID             uuid.UUID
	ProductID      uuid.UUID
	Sku            sql.NullString
	Barcode        sql.NullString
	Title          string
	PriceCents     int32
	CompareAtCents sql.NullInt32
	OptionValues   json.RawMessage
	Status         string
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, updateProductVariant,
		arg.ID,
		arg.ProductID,
		arg.Sku,
		arg.Barcode,
		arg.Title,
		arg.PriceCents,
		arg.CompareAtCents,
		arg.OptionValues,
		arg.Status,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StoreID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Title,
		&i.PriceCents,
		&i.CompareAtCents,
		&i.OptionValues,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
