// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: roles.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec

INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT (role_id, permission_id) DO NOTHING
`

type AssignPermissionToRoleParams struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

// Role-Permission Assignment
func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const assignRoleToTenantUser = `-- name: AssignRoleToTenantUser :exec

INSERT INTO tenant_user_roles (tenant_user_id, role_id)
VALUES ($1, $2)
ON CONFLICT (tenant_user_id, role_id) DO NOTHING
`

type AssignRoleToTenantUserParams struct {
	TenantUserID uuid.UUID
	RoleID       uuid.UUID
}

// Tenant User Role Assignment
func (q *Queries) AssignRoleToTenantUser(ctx context.Context, arg AssignRoleToTenantUserParams) error {
	_, err := q.db.ExecContext(ctx, assignRoleToTenantUser, arg.TenantUserID, arg.RoleID)
	return err
}

const checkUserHasPermission = `-- name: CheckUserHasPermission :one

SELECT EXISTS (
    SELECT 1 FROM tenant_users tu
    JOIN tenant_user_roles tur ON tu.id = tur.tenant_user_id
    JOIN role_permissions rp ON tur.role_id = rp.role_id
    JOIN permissions p ON rp.permission_id = p.id
    WHERE tu.tenant_id = $1
    AND tu.user_id = $2
    AND p.key = $3
    AND tu.status = 'active'
) AS has_permission
`

type CheckUserHasPermissionParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	Key      string
}

// Permission Checking Queries
func (q *Queries) CheckUserHasPermission(ctx context.Context, arg CheckUserHasPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserHasPermission, arg.TenantID, arg.UserID, arg.Key)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const createPermission = `-- name: CreatePermission :one

INSERT INTO permissions (id, key, description, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, now(), now())
RETURNING id, key, description, created_at, updated_at
`

type CreatePermissionParams struct {
	Key         string
	Description sql.NullString
}

// Permission Management
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, createPermission, arg.Key, arg.Description)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one

INSERT INTO roles (id, tenant_id, name, description, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, now(), now())
RETURNING id, tenant_id, name, description, created_at, updated_at
`

type CreateRoleParams struct {
	TenantID    uuid.UUID
	Name        string
	Description sql.NullString
}

// Role Management
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, arg.TenantID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const getAllPermissions = `-- name: GetAllPermissions :many
SELECT id, key, description, created_at, updated_at FROM permissions
ORDER BY key
`

func (q *Queries) GetAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, getAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, key, description, created_at, updated_at FROM permissions
WHERE id = $1
`

func (q *Queries) GetPermissionByID(ctx context.Context, id uuid.UUID) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPermissionByKey = `-- name: GetPermissionByKey :one
SELECT id, key, description, created_at, updated_at FROM permissions
WHERE key = $1
`

func (q *Queries) GetPermissionByKey(ctx context.Context, key string) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByKey, key)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPermissionsByKeys = `-- name: GetPermissionsByKeys :many
SELECT id, key, description, created_at, updated_at FROM permissions
WHERE key = ANY($1::text[])
ORDER BY key
`

func (q *Queries) GetPermissionsByKeys(ctx context.Context, dollar_1 []string) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, getPermissionsByKeys, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionsByRoleID = `-- name: GetPermissionsByRoleID :many
SELECT p.id, p.key, p.description, p.created_at, p.updated_at FROM permissions p
JOIN role_permissions rp ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.key
`

func (q *Queries) GetPermissionsByRoleID(ctx context.Context, roleID uuid.UUID) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, getPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, tenant_id, name, description, created_at, updated_at FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByTenantAndID = `-- name: GetRoleByTenantAndID :one
SELECT id, tenant_id, name, description, created_at, updated_at FROM roles
WHERE tenant_id = $1 AND id = $2
`

type GetRoleByTenantAndIDParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetRoleByTenantAndID(ctx context.Context, arg GetRoleByTenantAndIDParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByTenantAndID, arg.TenantID, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByTenantAndName = `-- name: GetRoleByTenantAndName :one
SELECT id, tenant_id, name, description, created_at, updated_at FROM roles
WHERE tenant_id = $1 AND name = $2
`

type GetRoleByTenantAndNameParams struct {
	TenantID uuid.UUID
	Name     string
}

func (q *Queries) GetRoleByTenantAndName(ctx context.Context, arg GetRoleByTenantAndNameParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByTenantAndName, arg.TenantID, arg.Name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolesByTenantID = `-- name: GetRolesByTenantID :many
SELECT id, tenant_id, name, description, created_at, updated_at FROM roles
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) GetRolesByTenantID(ctx context.Context, tenantID uuid.UUID) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRolesByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolesByTenantIDPaginated = `-- name: GetRolesByTenantIDPaginated :many
SELECT id, tenant_id, name, description, created_at, updated_at
FROM roles
WHERE tenant_id = $1
  AND (
    $2::boolean = false
    OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type GetRolesByTenantIDPaginatedParams struct {
	TenantID uuid.UUID
	Column2  bool
	Column3  time.Time
	Column4  uuid.UUID
	Limit    int32
}

func (q *Queries) GetRolesByTenantIDPaginated(ctx context.Context, arg GetRolesByTenantIDPaginatedParams) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRolesByTenantIDPaginated,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolesByTenantUserID = `-- name: GetRolesByTenantUserID :many
SELECT r.id, r.tenant_id, r.name, r.description, r.created_at, r.updated_at FROM roles r
JOIN tenant_user_roles tur ON r.id = tur.role_id
WHERE tur.tenant_user_id = $1
ORDER BY r.name
`

func (q *Queries) GetRolesByTenantUserID(ctx context.Context, tenantUserID uuid.UUID) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRolesByTenantUserID, tenantUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissionsInTenant = `-- name: GetUserPermissionsInTenant :many
SELECT DISTINCT p.id, p.key, p.description, p.created_at, p.updated_at FROM permissions p
JOIN role_permissions rp ON p.id = rp.permission_id
JOIN tenant_user_roles tur ON rp.role_id = tur.role_id
JOIN tenant_users tu ON tur.tenant_user_id = tu.id
WHERE tu.tenant_id = $1 AND tu.user_id = $2 AND tu.status = 'active'
ORDER BY p.key
`

type GetUserPermissionsInTenantParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetUserPermissionsInTenant(ctx context.Context, arg GetUserPermissionsInTenantParams) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, getUserPermissionsInTenant, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRolesInTenant = `-- name: GetUserRolesInTenant :many
SELECT r.id, r.tenant_id, r.name, r.description, r.created_at, r.updated_at FROM roles r
JOIN tenant_user_roles tur ON r.id = tur.role_id
JOIN tenant_users tu ON tur.tenant_user_id = tu.id
WHERE tu.tenant_id = $1 AND tu.user_id = $2 AND tu.status = 'active'
ORDER BY r.name
`

type GetUserRolesInTenantParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetUserRolesInTenant(ctx context.Context, arg GetUserRolesInTenantParams) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getUserRolesInTenant, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePermissionFromRole = `-- name: RemovePermissionFromRole :exec
DELETE FROM role_permissions
WHERE role_id = $1 AND permission_id = $2
`

type RemovePermissionFromRoleParams struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error {
	_, err := q.db.ExecContext(ctx, removePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}

const removeRoleFromTenantUser = `-- name: RemoveRoleFromTenantUser :exec
DELETE FROM tenant_user_roles
WHERE tenant_user_id = $1 AND role_id = $2
`

type RemoveRoleFromTenantUserParams struct {
	TenantUserID uuid.UUID
	RoleID       uuid.UUID
}

func (q *Queries) RemoveRoleFromTenantUser(ctx context.Context, arg RemoveRoleFromTenantUserParams) error {
	_, err := q.db.ExecContext(ctx, removeRoleFromTenantUser, arg.TenantUserID, arg.RoleID)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, description, created_at, updated_at
`

type UpdateRoleParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, updateRole, arg.ID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
