// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stores.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createStore = `-- name: CreateStore :one
insert into stores (id, name, handle, address, status, default_currency, timezone, plan, created_at, updated_at)
values (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, now(), now())
RETURNING id, name, handle, address, status, default_currency, timezone, plan, created_at, updated_at
`

type CreateStoreParams struct {
	Name            string
	Handle          string
	Address         sql.NullString
	Status          sql.NullString
	DefaultCurrency sql.NullString
	Timezone        sql.NullString
	Plan            sql.NullString
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRowContext(ctx, createStore,
		arg.Name,
		arg.Handle,
		arg.Address,
		arg.Status,
		arg.DefaultCurrency,
		arg.Timezone,
		arg.Plan,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Address,
		&i.Status,
		&i.DefaultCurrency,
		&i.Timezone,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllStores = `-- name: DeleteAllStores :exec
DELETE FROM stores
`

func (q *Queries) DeleteAllStores(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllStores)
	return err
}

const getAllStores = `-- name: GetAllStores :many
SELECT id, name, handle, address, status, default_currency, timezone, plan, created_at, updated_at FROM stores ORDER BY created_at ASC
`

func (q *Queries) GetAllStores(ctx context.Context) ([]Store, error) {
	rows, err := q.db.QueryContext(ctx, getAllStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Store
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handle,
			&i.Address,
			&i.Status,
			&i.DefaultCurrency,
			&i.Timezone,
			&i.Plan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreByHandle = `-- name: GetStoreByHandle :one
SELECT id, name, handle, address, status, default_currency, timezone, plan, created_at, updated_at FROM stores WHERE handle = $1
`

func (q *Queries) GetStoreByHandle(ctx context.Context, handle string) (Store, error) {
	row := q.db.QueryRowContext(ctx, getStoreByHandle, handle)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Address,
		&i.Status,
		&i.DefaultCurrency,
		&i.Timezone,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStore = `-- name: UpdateStore :one
UPDATE stores
SET 
    name = $2,
    handle = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, name, handle, address, status, default_currency, timezone, plan, created_at, updated_at
`

type UpdateStoreParams struct {
	ID     uuid.UUID
	Name   string
	Handle string
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error) {
	row := q.db.QueryRowContext(ctx, updateStore, arg.ID, arg.Name, arg.Handle)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Address,
		&i.Status,
		&i.DefaultCurrency,
		&i.Timezone,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
