// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tenants.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, gid, name, status, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, 'active', now(), now())
RETURNING id, name, status, created_at, updated_at, gid
`

type CreateTenantParams struct {
	Gid  sql.NullInt64
	Name string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant, arg.Gid, arg.Name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gid,
	)
	return i, err
}

const createTenantUser = `-- name: CreateTenantUser :one
INSERT INTO tenant_users (id, tenant_id, user_id, status, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, now(), now())
RETURNING id, tenant_id, user_id, status, created_at, updated_at
`

type CreateTenantUserParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	Status   string
}

func (q *Queries) CreateTenantUser(ctx context.Context, arg CreateTenantUserParams) (TenantUser, error) {
	row := q.db.QueryRowContext(ctx, createTenantUser, arg.TenantID, arg.UserID, arg.Status)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByGID = `-- name: GetTenantByGID :one
SELECT id, name, status, created_at, updated_at, gid FROM tenants
WHERE gid = $1
`

func (q *Queries) GetTenantByGID(ctx context.Context, gid sql.NullInt64) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByGID, gid)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gid,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, status, created_at, updated_at, gid FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gid,
	)
	return i, err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT id, name, status, created_at, updated_at, gid FROM tenants
WHERE name = $1
`

func (q *Queries) GetTenantByName(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByName, name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gid,
	)
	return i, err
}

const getTenantUser = `-- name: GetTenantUser :one
SELECT id, tenant_id, user_id, status, created_at, updated_at FROM tenant_users
WHERE tenant_id = $1 AND user_id = $2
`

type GetTenantUserParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetTenantUser(ctx context.Context, arg GetTenantUserParams) (TenantUser, error) {
	row := q.db.QueryRowContext(ctx, getTenantUser, arg.TenantID, arg.UserID)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantUserByID = `-- name: GetTenantUserByID :one
SELECT id, tenant_id, user_id, status, created_at, updated_at FROM tenant_users
WHERE id = $1
`

func (q *Queries) GetTenantUserByID(ctx context.Context, id uuid.UUID) (TenantUser, error) {
	row := q.db.QueryRowContext(ctx, getTenantUserByID, id)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantUsersByTenantID = `-- name: GetTenantUsersByTenantID :many
SELECT id, tenant_id, user_id, status, created_at, updated_at FROM tenant_users
WHERE tenant_id = $1
`

func (q *Queries) GetTenantUsersByTenantID(ctx context.Context, tenantID uuid.UUID) ([]TenantUser, error) {
	rows, err := q.db.QueryContext(ctx, getTenantUsersByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantUser
	for rows.Next() {
		var i TenantUser
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantUsersWithDetails = `-- name: GetTenantUsersWithDetails :many
SELECT tu.id, tu.tenant_id, tu.user_id, tu.status, tu.created_at, tu.updated_at, u.email FROM tenant_users tu
JOIN users u ON tu.user_id = u.id
WHERE tu.tenant_id = $1
`

type GetTenantUsersWithDetailsRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}

func (q *Queries) GetTenantUsersWithDetails(ctx context.Context, tenantID uuid.UUID) ([]GetTenantUsersWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTenantUsersWithDetails, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTenantUsersWithDetailsRow
	for rows.Next() {
		var i GetTenantUsersWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantUsersWithDetailsPaginated = `-- name: GetTenantUsersWithDetailsPaginated :many
SELECT tu.id, tu.tenant_id, tu.user_id, tu.status, tu.created_at, tu.updated_at, u.email
FROM tenant_users tu
JOIN users u ON tu.user_id = u.id
WHERE tu.tenant_id = $1
  AND (
    $2::boolean = false
    OR (tu.created_at, tu.id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY tu.created_at DESC, tu.id DESC
LIMIT $5
`

type GetTenantUsersWithDetailsPaginatedParams struct {
	TenantID uuid.UUID
	Column2  bool
	Column3  time.Time
	Column4  uuid.UUID
	Limit    int32
}

type GetTenantUsersWithDetailsPaginatedRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}

func (q *Queries) GetTenantUsersWithDetailsPaginated(ctx context.Context, arg GetTenantUsersWithDetailsPaginatedParams) ([]GetTenantUsersWithDetailsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getTenantUsersWithDetailsPaginated,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTenantUsersWithDetailsPaginatedRow
	for rows.Next() {
		var i GetTenantUsersWithDetailsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantsByUserID = `-- name: GetTenantsByUserID :many
SELECT t.id, t.name, t.status, t.created_at, t.updated_at, t.gid FROM tenants t
JOIN tenant_users tu ON t.id = tu.tenant_id
WHERE tu.user_id = $1 AND tu.status = 'active'
`

func (q *Queries) GetTenantsByUserID(ctx context.Context, userID uuid.UUID) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, getTenantsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantsByUserIDPaginated = `-- name: GetTenantsByUserIDPaginated :many
SELECT t.id, t.gid, t.name, t.status, t.created_at, t.updated_at
FROM tenants t
JOIN tenant_users tu ON t.id = tu.tenant_id
WHERE tu.user_id = $1
  AND tu.status = 'active'
  AND (
    $2::boolean = false
    OR (t.created_at, t.id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY t.created_at DESC, t.id DESC
LIMIT $5
`

type GetTenantsByUserIDPaginatedParams struct {
	UserID  uuid.UUID
	Column2 bool
	Column3 time.Time
	Column4 uuid.UUID
	Limit   int32
}

type GetTenantsByUserIDPaginatedRow struct {
	ID        uuid.UUID
	Gid       sql.NullInt64
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetTenantsByUserIDPaginated(ctx context.Context, arg GetTenantsByUserIDPaginatedParams) ([]GetTenantsByUserIDPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getTenantsByUserIDPaginated,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTenantsByUserIDPaginatedRow
	for rows.Next() {
		var i GetTenantsByUserIDPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Gid,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantStatus = `-- name: UpdateTenantStatus :one
UPDATE tenants
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, status, created_at, updated_at, gid
`

type UpdateTenantStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, updateTenantStatus, arg.ID, arg.Status)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gid,
	)
	return i, err
}

const updateTenantUserStatus = `-- name: UpdateTenantUserStatus :one
UPDATE tenant_users
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, user_id, status, created_at, updated_at
`

type UpdateTenantUserStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateTenantUserStatus(ctx context.Context, arg UpdateTenantUserStatusParams) (TenantUser, error) {
	row := q.db.QueryRowContext(ctx, updateTenantUserStatus, arg.ID, arg.Status)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
