export const countries = [
        { code: 'CA', name: 'Canada', emoji: '🇨🇦' },
        { code: 'US', name: 'United States', emoji: '🇺🇸' },
        { code: 'GB', name: 'United Kingdom', emoji: '🇬🇧' },
        { code: 'AU', name: 'Australia', emoji: '🇦🇺' },
        { code: 'DE', name: 'Germany', emoji: '🇩🇪' },
        { code: 'FR', name: 'France', emoji: '🇫🇷' },
        { code: 'ES', name: 'Spain', emoji: '🇪🇸' },
        { code: 'IT', name: 'Italy', emoji: '🇮🇹' },
        { code: 'NL', name: 'Netherlands', emoji: '🇳🇱' },
        { code: 'BE', name: 'Belgium', emoji: '🇧🇪' },
        { code: 'AT', name: 'Austria', emoji: '🇦🇹' },
        { code: 'CH', name: 'Switzerland', emoji: '🇨🇭' },
        { code: 'SE', name: 'Sweden', emoji: '🇸🇪' },
        { code: 'NO', name: 'Norway', emoji: '🇳🇴' },
        { code: 'DK', name: 'Denmark', emoji: '🇩🇰' },
        { code: 'FI', name: 'Finland', emoji: '🇫🇮' },
        { code: 'IE', name: 'Ireland', emoji: '🇮🇪' },
        { code: 'PT', name: 'Portugal', emoji: '🇵🇹' },
        { code: 'PL', name: 'Poland', emoji: '🇵🇱' },
        { code: 'CZ', name: 'Czech Republic', emoji: '🇨🇿' },
        { code: 'GR', name: 'Greece', emoji: '🇬🇷' },
        { code: 'RO', name: 'Romania', emoji: '🇷🇴' },
        { code: 'HU', name: 'Hungary', emoji: '🇭🇺' },
        { code: 'JP', name: 'Japan', emoji: '🇯🇵' },
        { code: 'KR', name: 'South Korea', emoji: '🇰🇷' },
        { code: 'CN', name: 'China', emoji: '🇨🇳' },
        { code: 'HK', name: 'Hong Kong', emoji: '🇭🇰' },
        { code: 'TW', name: 'Taiwan', emoji: '🇹🇼' },
        { code: 'SG', name: 'Singapore', emoji: '🇸🇬' },
        { code: 'MY', name: 'Malaysia', emoji: '🇲🇾' },
        { code: 'TH', name: 'Thailand', emoji: '🇹🇭' },
        { code: 'ID', name: 'Indonesia', emoji: '🇮🇩' },
        { code: 'PH', name: 'Philippines', emoji: '🇵🇭' },
        { code: 'VN', name: 'Vietnam', emoji: '🇻🇳' },
        { code: 'IN', name: 'India', emoji: '🇮🇳' },
        { code: 'PK', name: 'Pakistan', emoji: '🇵🇰' },
        { code: 'BD', name: 'Bangladesh', emoji: '🇧🇩' },
        { code: 'NZ', name: 'New Zealand', emoji: '🇳🇿' },
        { code: 'MX', name: 'Mexico', emoji: '🇲🇽' },
        { code: 'BR', name: 'Brazil', emoji: '🇧🇷' },
        { code: 'AR', name: 'Argentina', emoji: '🇦🇷' },
        { code: 'CL', name: 'Chile', emoji: '🇨🇱' },
        { code: 'CO', name: 'Colombia', emoji: '🇨🇴' },
        { code: 'PE', name: 'Peru', emoji: '🇵🇪' },
        { code: 'ZA', name: 'South Africa', emoji: '🇿🇦' },
        { code: 'NG', name: 'Nigeria', emoji: '🇳🇬' },
        { code: 'EG', name: 'Egypt', emoji: '🇪🇬' },
        { code: 'KE', name: 'Kenya', emoji: '🇰🇪' },
        { code: 'AE', name: 'United Arab Emirates', emoji: '🇦🇪' },
        { code: 'SA', name: 'Saudi Arabia', emoji: '🇸🇦' },
        { code: 'IL', name: 'Israel', emoji: '🇮🇱' },
        { code: 'TR', name: 'Turkey', emoji: '🇹🇷' },
        { code: 'RU', name: 'Russia', emoji: '🇷🇺' },
        { code: 'UA', name: 'Ukraine', emoji: '🇺🇦' },
    ];