// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_credentials.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPICredential = `-- name: CreateAPICredential :one

INSERT INTO api_credentials (
    organization_id, shop_id, name, key_prefix, key_hash,
    scopes, environment, status, created_by, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, organization_id, shop_id, name, key_prefix, key_hash, scopes, environment, status, last_used_at, created_by, created_at, updated_at, revoked_at, expires_at
`

type CreateAPICredentialParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	ShopID         pgtype.UUID        `json:"shop_id"`
	Name           string             `json:"name"`
	KeyPrefix      string             `json:"key_prefix"`
	KeyHash        string             `json:"key_hash"`
	Scopes         []string           `json:"scopes"`
	Environment    string             `json:"environment"`
	Status         string             `json:"status"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

// db/queries/api_credentials.sql
func (q *Queries) CreateAPICredential(ctx context.Context, arg CreateAPICredentialParams) (ApiCredential, error) {
	row := q.db.QueryRow(ctx, createAPICredential,
		arg.OrganizationID,
		arg.ShopID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Scopes,
		arg.Environment,
		arg.Status,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i ApiCredential
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Environment,
		&i.Status,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAPICredential = `-- name: DeleteAPICredential :exec
DELETE FROM api_credentials WHERE id = $1
`

func (q *Queries) DeleteAPICredential(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPICredential, id)
	return err
}

const getAPICredentialByID = `-- name: GetAPICredentialByID :one
SELECT id, organization_id, shop_id, name, key_prefix, key_hash, scopes, environment, status, last_used_at, created_by, created_at, updated_at, revoked_at, expires_at FROM api_credentials WHERE id = $1
`

func (q *Queries) GetAPICredentialByID(ctx context.Context, id uuid.UUID) (ApiCredential, error) {
	row := q.db.QueryRow(ctx, getAPICredentialByID, id)
	var i ApiCredential
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Environment,
		&i.Status,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAPICredentialByPrefix = `-- name: GetAPICredentialByPrefix :one
SELECT id, organization_id, shop_id, name, key_prefix, key_hash, scopes, environment, status, last_used_at, created_by, created_at, updated_at, revoked_at, expires_at FROM api_credentials
WHERE key_prefix = $1 AND status = 'active'
`

func (q *Queries) GetAPICredentialByPrefix(ctx context.Context, keyPrefix string) (ApiCredential, error) {
	row := q.db.QueryRow(ctx, getAPICredentialByPrefix, keyPrefix)
	var i ApiCredential
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Environment,
		&i.Status,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAPICredentialsByOrganization = `-- name: ListAPICredentialsByOrganization :many
SELECT id, organization_id, shop_id, name, key_prefix, key_hash, scopes, environment, status, last_used_at, created_by, created_at, updated_at, revoked_at, expires_at FROM api_credentials
WHERE organization_id = $1
  AND ($2::TEXT IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListAPICredentialsByOrganizationParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Status         pgtype.Text `json:"status"`
	Limit          int32       `json:"limit"`
}

func (q *Queries) ListAPICredentialsByOrganization(ctx context.Context, arg ListAPICredentialsByOrganizationParams) ([]ApiCredential, error) {
	rows, err := q.db.Query(ctx, listAPICredentialsByOrganization, arg.OrganizationID, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiCredential{}
	for rows.Next() {
		var i ApiCredential
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ShopID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Scopes,
			&i.Environment,
			&i.Status,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPICredentialsByShop = `-- name: ListAPICredentialsByShop :many
SELECT id, organization_id, shop_id, name, key_prefix, key_hash, scopes, environment, status, last_used_at, created_by, created_at, updated_at, revoked_at, expires_at FROM api_credentials
WHERE shop_id = $1
  AND ($2::TEXT IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListAPICredentialsByShopParams struct {
	ShopID pgtype.UUID `json:"shop_id"`
	Status pgtype.Text `json:"status"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListAPICredentialsByShop(ctx context.Context, arg ListAPICredentialsByShopParams) ([]ApiCredential, error) {
	rows, err := q.db.Query(ctx, listAPICredentialsByShop, arg.ShopID, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiCredential{}
	for rows.Next() {
		var i ApiCredential
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ShopID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Scopes,
			&i.Environment,
			&i.Status,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPICredential = `-- name: RevokeAPICredential :one
UPDATE api_credentials
SET status = 'revoked', revoked_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, shop_id, name, key_prefix, key_hash, scopes, environment, status, last_used_at, created_by, created_at, updated_at, revoked_at, expires_at
`

func (q *Queries) RevokeAPICredential(ctx context.Context, id uuid.UUID) (ApiCredential, error) {
	row := q.db.QueryRow(ctx, revokeAPICredential, id)
	var i ApiCredential
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Environment,
		&i.Status,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateAPICredential = `-- name: UpdateAPICredential :one
UPDATE api_credentials
SET
    name = COALESCE($2, name),
    scopes = COALESCE($3, scopes),
    expires_at = COALESCE($4, expires_at),
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, shop_id, name, key_prefix, key_hash, scopes, environment, status, last_used_at, created_by, created_at, updated_at, revoked_at, expires_at
`

type UpdateAPICredentialParams struct {
	ID        uuid.UUID          `json:"id"`
	Name      pgtype.Text        `json:"name"`
	Scopes    []string           `json:"scopes"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateAPICredential(ctx context.Context, arg UpdateAPICredentialParams) (ApiCredential, error) {
	row := q.db.QueryRow(ctx, updateAPICredential,
		arg.ID,
		arg.Name,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiCredential
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Environment,
		&i.Status,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateAPICredentialLastUsed = `-- name: UpdateAPICredentialLastUsed :exec
UPDATE api_credentials
SET last_used_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAPICredentialLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAPICredentialLastUsed, id)
	return err
}
