// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: customers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomersByOrganization = `-- name: CountCustomersByOrganization :one
SELECT COUNT(*) FROM customers
WHERE organization_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountCustomersByOrganization(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomersByOrganization, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCustomersByShop = `-- name: CountCustomersByShop :one
SELECT COUNT(*) FROM customers
WHERE shop_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountCustomersByShop(ctx context.Context, shopID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomersByShop, shopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one

INSERT INTO customers (
    shop_id, organization_id, email, phone, first_name, last_name,
    accepts_marketing, marketing_opt_in_at, tags, note, tax_exempt, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, shop_id, organization_id, email, phone, first_name, last_name, password_hash, accepts_marketing, marketing_opt_in_at, orders_count, total_spent_cents, tags, note, tax_exempt, status, created_at, updated_at, deleted_at
`

type CreateCustomerParams struct {
	ShopID           uuid.UUID          `json:"shop_id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	Email            string             `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
	FirstName        pgtype.Text        `json:"first_name"`
	LastName         pgtype.Text        `json:"last_name"`
	AcceptsMarketing bool               `json:"accepts_marketing"`
	MarketingOptInAt pgtype.Timestamptz `json:"marketing_opt_in_at"`
	Tags             []string           `json:"tags"`
	Note             pgtype.Text        `json:"note"`
	TaxExempt        bool               `json:"tax_exempt"`
	Status           string             `json:"status"`
}

// db/queries/customers.sql
func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.ShopID,
		arg.OrganizationID,
		arg.Email,
		arg.Phone,
		arg.FirstName,
		arg.LastName,
		arg.AcceptsMarketing,
		arg.MarketingOptInAt,
		arg.Tags,
		arg.Note,
		arg.TaxExempt,
		arg.Status,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.AcceptsMarketing,
		&i.MarketingOptInAt,
		&i.OrdersCount,
		&i.TotalSpentCents,
		&i.Tags,
		&i.Note,
		&i.TaxExempt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, shop_id, organization_id, email, phone, first_name, last_name, password_hash, accepts_marketing, marketing_opt_in_at, orders_count, total_spent_cents, tags, note, tax_exempt, status, created_at, updated_at, deleted_at FROM customers 
WHERE shop_id = $1 AND email = $2 AND deleted_at IS NULL
`

type GetCustomerByEmailParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	Email  string    `json:"email"`
}

func (q *Queries) GetCustomerByEmail(ctx context.Context, arg GetCustomerByEmailParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, arg.ShopID, arg.Email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.AcceptsMarketing,
		&i.MarketingOptInAt,
		&i.OrdersCount,
		&i.TotalSpentCents,
		&i.Tags,
		&i.Note,
		&i.TaxExempt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, shop_id, organization_id, email, phone, first_name, last_name, password_hash, accepts_marketing, marketing_opt_in_at, orders_count, total_spent_cents, tags, note, tax_exempt, status, created_at, updated_at, deleted_at FROM customers WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.AcceptsMarketing,
		&i.MarketingOptInAt,
		&i.OrdersCount,
		&i.TotalSpentCents,
		&i.Tags,
		&i.Note,
		&i.TaxExempt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCustomersByOrganization = `-- name: ListCustomersByOrganization :many
SELECT id, shop_id, organization_id, email, phone, first_name, last_name, password_hash, accepts_marketing, marketing_opt_in_at, orders_count, total_spent_cents, tags, note, tax_exempt, status, created_at, updated_at, deleted_at FROM customers
WHERE organization_id = $1 AND deleted_at IS NULL
  AND ($2::TEXT IS NULL OR status = $2)
  AND ($3::TIMESTAMPTZ IS NULL OR created_at < $3)
ORDER BY created_at DESC
LIMIT $4
`

type ListCustomersByOrganizationParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	Status         pgtype.Text        `json:"status"`
	Cursor         pgtype.Timestamptz `json:"cursor"`
	Limit          int32              `json:"limit"`
}

func (q *Queries) ListCustomersByOrganization(ctx context.Context, arg ListCustomersByOrganizationParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomersByOrganization,
		arg.OrganizationID,
		arg.Status,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.OrganizationID,
			&i.Email,
			&i.Phone,
			&i.FirstName,
			&i.LastName,
			&i.PasswordHash,
			&i.AcceptsMarketing,
			&i.MarketingOptInAt,
			&i.OrdersCount,
			&i.TotalSpentCents,
			&i.Tags,
			&i.Note,
			&i.TaxExempt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersByShop = `-- name: ListCustomersByShop :many
SELECT id, shop_id, organization_id, email, phone, first_name, last_name, password_hash, accepts_marketing, marketing_opt_in_at, orders_count, total_spent_cents, tags, note, tax_exempt, status, created_at, updated_at, deleted_at FROM customers
WHERE shop_id = $1 AND deleted_at IS NULL
  AND ($2::TEXT IS NULL OR status = $2)
  AND ($3::TIMESTAMPTZ IS NULL OR created_at < $3)
ORDER BY created_at DESC
LIMIT $4
`

type ListCustomersByShopParams struct {
	ShopID uuid.UUID          `json:"shop_id"`
	Status pgtype.Text        `json:"status"`
	Cursor pgtype.Timestamptz `json:"cursor"`
	Limit  int32              `json:"limit"`
}

func (q *Queries) ListCustomersByShop(ctx context.Context, arg ListCustomersByShopParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomersByShop,
		arg.ShopID,
		arg.Status,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.OrganizationID,
			&i.Email,
			&i.Phone,
			&i.FirstName,
			&i.LastName,
			&i.PasswordHash,
			&i.AcceptsMarketing,
			&i.MarketingOptInAt,
			&i.OrdersCount,
			&i.TotalSpentCents,
			&i.Tags,
			&i.Note,
			&i.TaxExempt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomers = `-- name: SearchCustomers :many
SELECT id, shop_id, organization_id, email, phone, first_name, last_name, password_hash, accepts_marketing, marketing_opt_in_at, orders_count, total_spent_cents, tags, note, tax_exempt, status, created_at, updated_at, deleted_at FROM customers
WHERE shop_id = $1 AND deleted_at IS NULL
  AND (
    email ILIKE '%' || $2 || '%' 
    OR first_name ILIKE '%' || $2 || '%'
    OR last_name ILIKE '%' || $2 || '%'
  )
ORDER BY created_at DESC
LIMIT $3
`

type SearchCustomersParams struct {
	ShopID uuid.UUID   `json:"shop_id"`
	Query  pgtype.Text `json:"query"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, searchCustomers, arg.ShopID, arg.Query, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.OrganizationID,
			&i.Email,
			&i.Phone,
			&i.FirstName,
			&i.LastName,
			&i.PasswordHash,
			&i.AcceptsMarketing,
			&i.MarketingOptInAt,
			&i.OrdersCount,
			&i.TotalSpentCents,
			&i.Tags,
			&i.Note,
			&i.TaxExempt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomerPassword = `-- name: SetCustomerPassword :exec
UPDATE customers
SET password_hash = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type SetCustomerPasswordParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) SetCustomerPassword(ctx context.Context, arg SetCustomerPasswordParams) error {
	_, err := q.db.Exec(ctx, setCustomerPassword, arg.ID, arg.PasswordHash)
	return err
}

const softDeleteCustomer = `-- name: SoftDeleteCustomer :exec
UPDATE customers SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteCustomer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCustomer, id)
	return err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET
    email = COALESCE($2, email),
    phone = COALESCE($3, phone),
    first_name = COALESCE($4, first_name),
    last_name = COALESCE($5, last_name),
    accepts_marketing = COALESCE($6, accepts_marketing),
    tags = COALESCE($7, tags),
    note = COALESCE($8, note),
    tax_exempt = COALESCE($9, tax_exempt),
    status = COALESCE($10, status),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, shop_id, organization_id, email, phone, first_name, last_name, password_hash, accepts_marketing, marketing_opt_in_at, orders_count, total_spent_cents, tags, note, tax_exempt, status, created_at, updated_at, deleted_at
`

type UpdateCustomerParams struct {
	ID               uuid.UUID   `json:"id"`
	Email            pgtype.Text `json:"email"`
	Phone            pgtype.Text `json:"phone"`
	FirstName        pgtype.Text `json:"first_name"`
	LastName         pgtype.Text `json:"last_name"`
	AcceptsMarketing pgtype.Bool `json:"accepts_marketing"`
	Tags             []string    `json:"tags"`
	Note             pgtype.Text `json:"note"`
	TaxExempt        pgtype.Bool `json:"tax_exempt"`
	Status           pgtype.Text `json:"status"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.Email,
		arg.Phone,
		arg.FirstName,
		arg.LastName,
		arg.AcceptsMarketing,
		arg.Tags,
		arg.Note,
		arg.TaxExempt,
		arg.Status,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.AcceptsMarketing,
		&i.MarketingOptInAt,
		&i.OrdersCount,
		&i.TotalSpentCents,
		&i.Tags,
		&i.Note,
		&i.TaxExempt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCustomerStats = `-- name: UpdateCustomerStats :exec
UPDATE customers
SET 
    orders_count = orders_count + 1,
    total_spent_cents = total_spent_cents + $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCustomerStatsParams struct {
	ID          uuid.UUID `json:"id"`
	AmountCents int64     `json:"amount_cents"`
}

func (q *Queries) UpdateCustomerStats(ctx context.Context, arg UpdateCustomerStatsParams) error {
	_, err := q.db.Exec(ctx, updateCustomerStats, arg.ID, arg.AmountCents)
	return err
}

const updateMarketingOptIn = `-- name: UpdateMarketingOptIn :one
UPDATE customers
SET 
    accepts_marketing = $2,
    marketing_opt_in_at = CASE WHEN $2 = TRUE THEN NOW() ELSE marketing_opt_in_at END,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, shop_id, organization_id, email, phone, first_name, last_name, password_hash, accepts_marketing, marketing_opt_in_at, orders_count, total_spent_cents, tags, note, tax_exempt, status, created_at, updated_at, deleted_at
`

type UpdateMarketingOptInParams struct {
	ID               uuid.UUID `json:"id"`
	AcceptsMarketing bool      `json:"accepts_marketing"`
}

func (q *Queries) UpdateMarketingOptIn(ctx context.Context, arg UpdateMarketingOptInParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateMarketingOptIn, arg.ID, arg.AcceptsMarketing)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.AcceptsMarketing,
		&i.MarketingOptInAt,
		&i.OrdersCount,
		&i.TotalSpentCents,
		&i.Tags,
		&i.Note,
		&i.TaxExempt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertCustomer = `-- name: UpsertCustomer :one
INSERT INTO customers (shop_id, organization_id, email, phone, first_name, last_name)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (shop_id, email) 
DO UPDATE SET
    phone = COALESCE(EXCLUDED.phone, customers.phone),
    first_name = COALESCE(EXCLUDED.first_name, customers.first_name),
    last_name = COALESCE(EXCLUDED.last_name, customers.last_name),
    updated_at = NOW()
RETURNING id, shop_id, organization_id, email, phone, first_name, last_name, password_hash, accepts_marketing, marketing_opt_in_at, orders_count, total_spent_cents, tags, note, tax_exempt, status, created_at, updated_at, deleted_at
`

type UpsertCustomerParams struct {
	ShopID         uuid.UUID   `json:"shop_id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	Email          string      `json:"email"`
	Phone          pgtype.Text `json:"phone"`
	FirstName      pgtype.Text `json:"first_name"`
	LastName       pgtype.Text `json:"last_name"`
}

func (q *Queries) UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, upsertCustomer,
		arg.ShopID,
		arg.OrganizationID,
		arg.Email,
		arg.Phone,
		arg.FirstName,
		arg.LastName,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.AcceptsMarketing,
		&i.MarketingOptInAt,
		&i.OrdersCount,
		&i.TotalSpentCents,
		&i.Tags,
		&i.Note,
		&i.TaxExempt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
