// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	FirstName      pgtype.Text `json:"first_name"`
	LastName       pgtype.Text `json:"last_name"`
	Company        pgtype.Text `json:"company"`
	Address1       string      `json:"address1"`
	Address2       pgtype.Text `json:"address2"`
	City           string      `json:"city"`
	Province       pgtype.Text `json:"province"`
	ProvinceCode   pgtype.Text `json:"province_code"`
	Country        string      `json:"country"`
	CountryCode    string      `json:"country_code"`
	Zip            pgtype.Text `json:"zip"`
	Phone          pgtype.Text `json:"phone"`
	Label          pgtype.Text `json:"label"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type ApiCredential struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ShopID         pgtype.UUID        `json:"shop_id"`
	Name           string             `json:"name"`
	KeyPrefix      string             `json:"key_prefix"`
	KeyHash        string             `json:"key_hash"`
	Scopes         []string           `json:"scopes"`
	Environment    string             `json:"environment"`
	Status         string             `json:"status"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type AuditLog struct {
	ID              uuid.UUID   `json:"id"`
	OrganizationID  uuid.UUID   `json:"organization_id"`
	ShopID          pgtype.UUID `json:"shop_id"`
	UserID          pgtype.UUID `json:"user_id"`
	Action          string      `json:"action"`
	ResourceType    string      `json:"resource_type"`
	ResourceID      pgtype.UUID `json:"resource_id"`
	Changes         []byte      `json:"changes"`
	IpAddress       *netip.Addr `json:"ip_address"`
	UserAgent       pgtype.Text `json:"user_agent"`
	ApiCredentialID pgtype.UUID `json:"api_credential_id"`
	CreatedAt       time.Time   `json:"created_at"`
}

type Collection struct {
	ID              uuid.UUID          `json:"id"`
	ShopID          uuid.UUID          `json:"shop_id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Description     pgtype.Text        `json:"description"`
	DescriptionHtml pgtype.Text        `json:"description_html"`
	CollectionType  string             `json:"collection_type"`
	Rules           []byte             `json:"rules"`
	Disjunctive     bool               `json:"disjunctive"`
	ImageUrl        pgtype.Text        `json:"image_url"`
	SeoTitle        pgtype.Text        `json:"seo_title"`
	SeoDescription  pgtype.Text        `json:"seo_description"`
	SortOrder       string             `json:"sort_order"`
	Published       bool               `json:"published"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type CollectionProduct struct {
	ID           uuid.UUID `json:"id"`
	CollectionID uuid.UUID `json:"collection_id"`
	ProductID    uuid.UUID `json:"product_id"`
	Position     int32     `json:"position"`
	CreatedAt    time.Time `json:"created_at"`
}

type Customer struct {
	ID               uuid.UUID          `json:"id"`
	ShopID           uuid.UUID          `json:"shop_id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	Email            string             `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
	FirstName        pgtype.Text        `json:"first_name"`
	LastName         pgtype.Text        `json:"last_name"`
	PasswordHash     pgtype.Text        `json:"password_hash"`
	AcceptsMarketing bool               `json:"accepts_marketing"`
	MarketingOptInAt pgtype.Timestamptz `json:"marketing_opt_in_at"`
	OrdersCount      int32              `json:"orders_count"`
	TotalSpentCents  int64              `json:"total_spent_cents"`
	Tags             []string           `json:"tags"`
	Note             pgtype.Text        `json:"note"`
	TaxExempt        bool               `json:"tax_exempt"`
	Status           string             `json:"status"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type CustomerAddress struct {
	ID                uuid.UUID `json:"id"`
	CustomerID        uuid.UUID `json:"customer_id"`
	AddressID         uuid.UUID `json:"address_id"`
	ShopID            uuid.UUID `json:"shop_id"`
	IsDefaultBilling  bool      `json:"is_default_billing"`
	IsDefaultShipping bool      `json:"is_default_shipping"`
	CreatedAt         time.Time `json:"created_at"`
}

type Fulfillment struct {
	ID              uuid.UUID   `json:"id"`
	OrderID         uuid.UUID   `json:"order_id"`
	ShopID          uuid.UUID   `json:"shop_id"`
	Status          string      `json:"status"`
	TrackingCompany pgtype.Text `json:"tracking_company"`
	TrackingNumber  pgtype.Text `json:"tracking_number"`
	TrackingUrl     pgtype.Text `json:"tracking_url"`
	TrackingNumbers []string    `json:"tracking_numbers"`
	TrackingUrls    []string    `json:"tracking_urls"`
	ShipmentStatus  pgtype.Text `json:"shipment_status"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type FulfillmentLineItem struct {
	ID              uuid.UUID `json:"id"`
	FulfillmentID   uuid.UUID `json:"fulfillment_id"`
	OrderLineItemID uuid.UUID `json:"order_line_item_id"`
	Quantity        int32     `json:"quantity"`
	CreatedAt       time.Time `json:"created_at"`
}

type Order struct {
	ID                uuid.UUID          `json:"id"`
	ShopID            uuid.UUID          `json:"shop_id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	OrderNumber       int64              `json:"order_number"`
	Email             string             `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	Currency          string             `json:"currency"`
	SubtotalCents     int64              `json:"subtotal_cents"`
	DiscountCents     int64              `json:"discount_cents"`
	ShippingCents     int64              `json:"shipping_cents"`
	TaxCents          int64              `json:"tax_cents"`
	TotalCents        int64              `json:"total_cents"`
	RefundedCents     int64              `json:"refunded_cents"`
	Status            string             `json:"status"`
	FinancialStatus   string             `json:"financial_status"`
	FulfillmentStatus pgtype.Text        `json:"fulfillment_status"`
	ShippingAddress   []byte             `json:"shipping_address"`
	BillingAddress    []byte             `json:"billing_address"`
	Note              pgtype.Text        `json:"note"`
	NoteAttributes    []byte             `json:"note_attributes"`
	Tags              []string           `json:"tags"`
	SourceName        string             `json:"source_name"`
	SourceIdentifier  pgtype.Text        `json:"source_identifier"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	ProcessedAt       pgtype.Timestamptz `json:"processed_at"`
	CancelledAt       pgtype.Timestamptz `json:"cancelled_at"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
}

type OrderLineItem struct {
	ID                  uuid.UUID   `json:"id"`
	OrderID             uuid.UUID   `json:"order_id"`
	ShopID              uuid.UUID   `json:"shop_id"`
	ProductID           pgtype.UUID `json:"product_id"`
	VariantID           pgtype.UUID `json:"variant_id"`
	Title               string      `json:"title"`
	VariantTitle        pgtype.Text `json:"variant_title"`
	Sku                 pgtype.Text `json:"sku"`
	Quantity            int32       `json:"quantity"`
	FulfillableQuantity int32       `json:"fulfillable_quantity"`
	FulfilledQuantity   int32       `json:"fulfilled_quantity"`
	UnitPriceCents      int64       `json:"unit_price_cents"`
	DiscountCents       int64       `json:"discount_cents"`
	TotalCents          int64       `json:"total_cents"`
	Taxable             bool        `json:"taxable"`
	TaxLines            []byte      `json:"tax_lines"`
	RequiresShipping    bool        `json:"requires_shipping"`
	Properties          []byte      `json:"properties"`
	CreatedAt           time.Time   `json:"created_at"`
}

type Organization struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	Handle           string             `json:"handle"`
	Plan             string             `json:"plan"`
	BillingEmail     pgtype.Text        `json:"billing_email"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
	Status           string             `json:"status"`
	MaxShops         int32              `json:"max_shops"`
	MaxMembers       int32              `json:"max_members"`
	Settings         json.RawMessage    `json:"settings"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type OrganizationMember struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Role           string             `json:"role"`
	InvitedBy      pgtype.UUID        `json:"invited_by"`
	InvitedAt      pgtype.Timestamptz `json:"invited_at"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type Product struct {
	ID                  uuid.UUID          `json:"id"`
	ShopID              uuid.UUID          `json:"shop_id"`
	OrganizationID      uuid.UUID          `json:"organization_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	DescriptionHtml     pgtype.Text        `json:"description_html"`
	Handle              string             `json:"handle"`
	PriceCents          int64              `json:"price_cents"`
	CompareAtPriceCents pgtype.Int8        `json:"compare_at_price_cents"`
	CostCents           pgtype.Int8        `json:"cost_cents"`
	Vendor              pgtype.Text        `json:"vendor"`
	ProductType         pgtype.Text        `json:"product_type"`
	Tags                []string           `json:"tags"`
	Sku                 pgtype.Text        `json:"sku"`
	Barcode             pgtype.Text        `json:"barcode"`
	InventoryQuantity   int32              `json:"inventory_quantity"`
	TrackInventory      bool               `json:"track_inventory"`
	Status              string             `json:"status"`
	SeoTitle            pgtype.Text        `json:"seo_title"`
	SeoDescription      pgtype.Text        `json:"seo_description"`
	TemplateSuffix      pgtype.Text        `json:"template_suffix"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type ProductImage struct {
	ID         uuid.UUID   `json:"id"`
	ProductID  uuid.UUID   `json:"product_id"`
	ShopID     uuid.UUID   `json:"shop_id"`
	Src        string      `json:"src"`
	Alt        pgtype.Text `json:"alt"`
	Width      pgtype.Int4 `json:"width"`
	Height     pgtype.Int4 `json:"height"`
	Position   int32       `json:"position"`
	VariantIds []uuid.UUID `json:"variant_ids"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type ProductVariant struct {
	ID                  uuid.UUID          `json:"id"`
	ProductID           uuid.UUID          `json:"product_id"`
	ShopID              uuid.UUID          `json:"shop_id"`
	Title               string             `json:"title"`
	PriceCents          int64              `json:"price_cents"`
	CompareAtPriceCents pgtype.Int8        `json:"compare_at_price_cents"`
	CostCents           pgtype.Int8        `json:"cost_cents"`
	Sku                 pgtype.Text        `json:"sku"`
	Barcode             pgtype.Text        `json:"barcode"`
	InventoryQuantity   int32              `json:"inventory_quantity"`
	InventoryPolicy     string             `json:"inventory_policy"`
	Option1Name         pgtype.Text        `json:"option1_name"`
	Option1Value        pgtype.Text        `json:"option1_value"`
	Option2Name         pgtype.Text        `json:"option2_name"`
	Option2Value        pgtype.Text        `json:"option2_value"`
	Option3Name         pgtype.Text        `json:"option3_name"`
	Option3Value        pgtype.Text        `json:"option3_value"`
	WeightGrams         pgtype.Int4        `json:"weight_grams"`
	RequiresShipping    bool               `json:"requires_shipping"`
	Position            int32              `json:"position"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type Shop struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Gid            pgtype.Int8        `json:"gid"`
	Name           string             `json:"name"`
	Handle         string             `json:"handle"`
	Subdomain      string             `json:"subdomain"`
	CustomDomain   pgtype.Text        `json:"custom_domain"`
	Currency       string             `json:"currency"`
	Locale         string             `json:"locale"`
	Timezone       string             `json:"timezone"`
	ShopOwner      pgtype.Text        `json:"shop_owner"`
	Email          pgtype.Text        `json:"email"`
	Phone          pgtype.Text        `json:"phone"`
	Source         string             `json:"source"`
	ReferralCode   pgtype.Text        `json:"referral_code"`
	Status         string             `json:"status"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type ShopAddress struct {
	ID          uuid.UUID `json:"id"`
	ShopID      uuid.UUID `json:"shop_id"`
	AddressID   uuid.UUID `json:"address_id"`
	AddressType string    `json:"address_type"`
	IsDefault   bool      `json:"is_default"`
	CreatedAt   time.Time `json:"created_at"`
}

type ShopMember struct {
	ID             uuid.UUID `json:"id"`
	ShopID         uuid.UUID `json:"shop_id"`
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Role           string    `json:"role"`
	Permissions    []string  `json:"permissions"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ShopSequence struct {
	ShopID      uuid.UUID `json:"shop_id"`
	OrderNumber int64     `json:"order_number"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Theme struct {
	ID               uuid.UUID          `json:"id"`
	ShopID           uuid.UUID          `json:"shop_id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	Name             string             `json:"name"`
	Handle           string             `json:"handle"`
	SourceType       string             `json:"source_type"`
	SourceThemeID    pgtype.UUID        `json:"source_theme_id"`
	Version          pgtype.Text        `json:"version"`
	Role             string             `json:"role"`
	ProcessingStatus string             `json:"processing_status"`
	ProcessingError  pgtype.Text        `json:"processing_error"`
	StorageBucket    string             `json:"storage_bucket"`
	StoragePrefix    string             `json:"storage_prefix"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
}

type ThemeSetting struct {
	ID            uuid.UUID       `json:"id"`
	ThemeID       uuid.UUID       `json:"theme_id"`
	SettingsData  json.RawMessage `json:"settings_data"`
	TemplatesData json.RawMessage `json:"templates_data"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Transaction struct {
	ID                   uuid.UUID          `json:"id"`
	OrderID              uuid.UUID          `json:"order_id"`
	ShopID               uuid.UUID          `json:"shop_id"`
	Kind                 string             `json:"kind"`
	AmountCents          int64              `json:"amount_cents"`
	Currency             string             `json:"currency"`
	Status               string             `json:"status"`
	Gateway              string             `json:"gateway"`
	GatewayTransactionID pgtype.Text        `json:"gateway_transaction_id"`
	ErrorCode            pgtype.Text        `json:"error_code"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
	ParentID             pgtype.UUID        `json:"parent_id"`
	CreatedAt            time.Time          `json:"created_at"`
	ProcessedAt          pgtype.Timestamptz `json:"processed_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	FirstName     pgtype.Text        `json:"first_name"`
	LastName      pgtype.Text        `json:"last_name"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	Phone         pgtype.Text        `json:"phone"`
	Status        string             `json:"status"`
	Locale        string             `json:"locale"`
	Timezone      string             `json:"timezone"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Webhook struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	ShopID            pgtype.UUID        `json:"shop_id"`
	Topic             string             `json:"topic"`
	EndpointUrl       string             `json:"endpoint_url"`
	SecretHash        string             `json:"secret_hash"`
	Fields            []string           `json:"fields"`
	Status            string             `json:"status"`
	FailureCount      int32              `json:"failure_count"`
	LastFailureAt     pgtype.Timestamptz `json:"last_failure_at"`
	LastFailureReason pgtype.Text        `json:"last_failure_reason"`
	ApiVersion        string             `json:"api_version"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type WebhookDelivery struct {
	ID              uuid.UUID          `json:"id"`
	WebhookID       uuid.UUID          `json:"webhook_id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	ShopID          pgtype.UUID        `json:"shop_id"`
	Topic           string             `json:"topic"`
	EndpointUrl     string             `json:"endpoint_url"`
	RequestHeaders  []byte             `json:"request_headers"`
	RequestBody     []byte             `json:"request_body"`
	ResponseStatus  pgtype.Int4        `json:"response_status"`
	ResponseHeaders []byte             `json:"response_headers"`
	ResponseBody    []byte             `json:"response_body"`
	Status          string             `json:"status"`
	Attempts        int32              `json:"attempts"`
	NextRetryAt     pgtype.Timestamptz `json:"next_retry_at"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	DurationMs      pgtype.Int4        `json:"duration_ms"`
	CreatedAt       time.Time          `json:"created_at"`
	DeliveredAt     pgtype.Timestamptz `json:"delivered_at"`
}
