// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oauth_installations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthInstallation = `-- name: CreateOAuthInstallation :one

INSERT INTO oauth_installations (
    shop_id, app_id, access_token_hash, scopes, status
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, shop_id, app_id, access_token_hash, scopes, status, installed_at, uninstalled_at, created_at, updated_at
`

type CreateOAuthInstallationParams struct {
	ShopID          uuid.UUID `json:"shop_id"`
	AppID           uuid.UUID `json:"app_id"`
	AccessTokenHash string    `json:"access_token_hash"`
	Scopes          []string  `json:"scopes"`
	Status          string    `json:"status"`
}

// db/queries/oauth_installations.sql
func (q *Queries) CreateOAuthInstallation(ctx context.Context, arg CreateOAuthInstallationParams) (OauthInstallation, error) {
	row := q.db.QueryRow(ctx, createOAuthInstallation,
		arg.ShopID,
		arg.AppID,
		arg.AccessTokenHash,
		arg.Scopes,
		arg.Status,
	)
	var i OauthInstallation
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.AppID,
		&i.AccessTokenHash,
		&i.Scopes,
		&i.Status,
		&i.InstalledAt,
		&i.UninstalledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOAuthInstallation = `-- name: DeleteOAuthInstallation :exec
DELETE FROM oauth_installations WHERE id = $1
`

func (q *Queries) DeleteOAuthInstallation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuthInstallation, id)
	return err
}

const getOAuthInstallationByAccessToken = `-- name: GetOAuthInstallationByAccessToken :one
SELECT id, shop_id, app_id, access_token_hash, scopes, status, installed_at, uninstalled_at, created_at, updated_at FROM oauth_installations
WHERE access_token_hash = $1 AND status = 'active'
`

func (q *Queries) GetOAuthInstallationByAccessToken(ctx context.Context, accessTokenHash string) (OauthInstallation, error) {
	row := q.db.QueryRow(ctx, getOAuthInstallationByAccessToken, accessTokenHash)
	var i OauthInstallation
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.AppID,
		&i.AccessTokenHash,
		&i.Scopes,
		&i.Status,
		&i.InstalledAt,
		&i.UninstalledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthInstallationByID = `-- name: GetOAuthInstallationByID :one
SELECT id, shop_id, app_id, access_token_hash, scopes, status, installed_at, uninstalled_at, created_at, updated_at FROM oauth_installations WHERE id = $1
`

func (q *Queries) GetOAuthInstallationByID(ctx context.Context, id uuid.UUID) (OauthInstallation, error) {
	row := q.db.QueryRow(ctx, getOAuthInstallationByID, id)
	var i OauthInstallation
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.AppID,
		&i.AccessTokenHash,
		&i.Scopes,
		&i.Status,
		&i.InstalledAt,
		&i.UninstalledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthInstallationByShopAndApp = `-- name: GetOAuthInstallationByShopAndApp :one
SELECT id, shop_id, app_id, access_token_hash, scopes, status, installed_at, uninstalled_at, created_at, updated_at FROM oauth_installations
WHERE shop_id = $1 AND app_id = $2
`

type GetOAuthInstallationByShopAndAppParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	AppID  uuid.UUID `json:"app_id"`
}

func (q *Queries) GetOAuthInstallationByShopAndApp(ctx context.Context, arg GetOAuthInstallationByShopAndAppParams) (OauthInstallation, error) {
	row := q.db.QueryRow(ctx, getOAuthInstallationByShopAndApp, arg.ShopID, arg.AppID)
	var i OauthInstallation
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.AppID,
		&i.AccessTokenHash,
		&i.Scopes,
		&i.Status,
		&i.InstalledAt,
		&i.UninstalledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOAuthInstallationsByShop = `-- name: ListOAuthInstallationsByShop :many
SELECT id, shop_id, app_id, access_token_hash, scopes, status, installed_at, uninstalled_at, created_at, updated_at FROM oauth_installations
WHERE shop_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOAuthInstallationsByShop(ctx context.Context, shopID uuid.UUID) ([]OauthInstallation, error) {
	rows, err := q.db.Query(ctx, listOAuthInstallationsByShop, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthInstallation{}
	for rows.Next() {
		var i OauthInstallation
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.AppID,
			&i.AccessTokenHash,
			&i.Scopes,
			&i.Status,
			&i.InstalledAt,
			&i.UninstalledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uninstallOAuthInstallation = `-- name: UninstallOAuthInstallation :one
UPDATE oauth_installations
SET status = 'uninstalled', uninstalled_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, shop_id, app_id, access_token_hash, scopes, status, installed_at, uninstalled_at, created_at, updated_at
`

func (q *Queries) UninstallOAuthInstallation(ctx context.Context, id uuid.UUID) (OauthInstallation, error) {
	row := q.db.QueryRow(ctx, uninstallOAuthInstallation, id)
	var i OauthInstallation
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.AppID,
		&i.AccessTokenHash,
		&i.Scopes,
		&i.Status,
		&i.InstalledAt,
		&i.UninstalledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOAuthInstallation = `-- name: UpdateOAuthInstallation :one
UPDATE oauth_installations
SET
    access_token_hash = COALESCE($2, access_token_hash),
    scopes = COALESCE($3, scopes),
    status = COALESCE($4, status),
    updated_at = NOW()
WHERE id = $1
RETURNING id, shop_id, app_id, access_token_hash, scopes, status, installed_at, uninstalled_at, created_at, updated_at
`

type UpdateOAuthInstallationParams struct {
	ID              uuid.UUID   `json:"id"`
	AccessTokenHash pgtype.Text `json:"access_token_hash"`
	Scopes          []string    `json:"scopes"`
	Status          pgtype.Text `json:"status"`
}

func (q *Queries) UpdateOAuthInstallation(ctx context.Context, arg UpdateOAuthInstallationParams) (OauthInstallation, error) {
	row := q.db.QueryRow(ctx, updateOAuthInstallation,
		arg.ID,
		arg.AccessTokenHash,
		arg.Scopes,
		arg.Status,
	)
	var i OauthInstallation
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.AppID,
		&i.AccessTokenHash,
		&i.Scopes,
		&i.Status,
		&i.InstalledAt,
		&i.UninstalledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
