// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET status = 'cancelled', cancelled_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, shop_id, organization_id, customer_id, order_number, email, phone, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, refunded_cents, status, financial_status, fulfillment_status, shipping_address, billing_address, note, note_attributes, tags, source_name, source_identifier, created_at, updated_at, processed_at, cancelled_at, closed_at
`

func (q *Queries) CancelOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, cancelOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Email,
		&i.Phone,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.RefundedCents,
		&i.Status,
		&i.FinancialStatus,
		&i.FulfillmentStatus,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.Note,
		&i.NoteAttributes,
		&i.Tags,
		&i.SourceName,
		&i.SourceIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
		&i.CancelledAt,
		&i.ClosedAt,
	)
	return i, err
}

const closeOrder = `-- name: CloseOrder :one
UPDATE orders
SET status = 'archived', closed_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, shop_id, organization_id, customer_id, order_number, email, phone, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, refunded_cents, status, financial_status, fulfillment_status, shipping_address, billing_address, note, note_attributes, tags, source_name, source_identifier, created_at, updated_at, processed_at, cancelled_at, closed_at
`

func (q *Queries) CloseOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, closeOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Email,
		&i.Phone,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.RefundedCents,
		&i.Status,
		&i.FinancialStatus,
		&i.FulfillmentStatus,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.Note,
		&i.NoteAttributes,
		&i.Tags,
		&i.SourceName,
		&i.SourceIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
		&i.CancelledAt,
		&i.ClosedAt,
	)
	return i, err
}

const confirmOrder = `-- name: ConfirmOrder :one
UPDATE orders
SET status = 'confirmed', processed_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, shop_id, organization_id, customer_id, order_number, email, phone, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, refunded_cents, status, financial_status, fulfillment_status, shipping_address, billing_address, note, note_attributes, tags, source_name, source_identifier, created_at, updated_at, processed_at, cancelled_at, closed_at
`

func (q *Queries) ConfirmOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, confirmOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Email,
		&i.Phone,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.RefundedCents,
		&i.Status,
		&i.FinancialStatus,
		&i.FulfillmentStatus,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.Note,
		&i.NoteAttributes,
		&i.Tags,
		&i.SourceName,
		&i.SourceIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
		&i.CancelledAt,
		&i.ClosedAt,
	)
	return i, err
}

const countOrdersByCustomer = `-- name: CountOrdersByCustomer :one
SELECT COUNT(*) FROM orders WHERE customer_id = $1
`

func (q *Queries) CountOrdersByCustomer(ctx context.Context, customerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByCustomer, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByShop = `-- name: CountOrdersByShop :one
SELECT COUNT(*) FROM orders
WHERE shop_id = $1
  AND ($2::TEXT IS NULL OR status = $2)
`

type CountOrdersByShopParams struct {
	ShopID uuid.UUID   `json:"shop_id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) CountOrdersByShop(ctx context.Context, arg CountOrdersByShopParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByShop, arg.ShopID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders (
    shop_id, organization_id, customer_id, order_number, email, phone,
    currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents,
    status, financial_status, fulfillment_status,
    shipping_address, billing_address, note, note_attributes, tags,
    source_name, source_identifier
) VALUES (
    $1, $2, $3, next_order_number($1), $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17, $18, $19,
    $20, $21
)
RETURNING id, shop_id, organization_id, customer_id, order_number, email, phone, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, refunded_cents, status, financial_status, fulfillment_status, shipping_address, billing_address, note, note_attributes, tags, source_name, source_identifier, created_at, updated_at, processed_at, cancelled_at, closed_at
`

type CreateOrderParams struct {
	ShopID            uuid.UUID   `json:"shop_id"`
	OrganizationID    uuid.UUID   `json:"organization_id"`
	CustomerID        pgtype.UUID `json:"customer_id"`
	Email             string      `json:"email"`
	Phone             pgtype.Text `json:"phone"`
	Currency          string      `json:"currency"`
	SubtotalCents     int64       `json:"subtotal_cents"`
	DiscountCents     int64       `json:"discount_cents"`
	ShippingCents     int64       `json:"shipping_cents"`
	TaxCents          int64       `json:"tax_cents"`
	TotalCents        int64       `json:"total_cents"`
	Status            string      `json:"status"`
	FinancialStatus   string      `json:"financial_status"`
	FulfillmentStatus pgtype.Text `json:"fulfillment_status"`
	ShippingAddress   []byte      `json:"shipping_address"`
	BillingAddress    []byte      `json:"billing_address"`
	Note              pgtype.Text `json:"note"`
	NoteAttributes    []byte      `json:"note_attributes"`
	Tags              []string    `json:"tags"`
	SourceName        string      `json:"source_name"`
	SourceIdentifier  pgtype.Text `json:"source_identifier"`
}

// db/queries/orders.sql
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ShopID,
		arg.OrganizationID,
		arg.CustomerID,
		arg.Email,
		arg.Phone,
		arg.Currency,
		arg.SubtotalCents,
		arg.DiscountCents,
		arg.ShippingCents,
		arg.TaxCents,
		arg.TotalCents,
		arg.Status,
		arg.FinancialStatus,
		arg.FulfillmentStatus,
		arg.ShippingAddress,
		arg.BillingAddress,
		arg.Note,
		arg.NoteAttributes,
		arg.Tags,
		arg.SourceName,
		arg.SourceIdentifier,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Email,
		&i.Phone,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.RefundedCents,
		&i.Status,
		&i.FinancialStatus,
		&i.FulfillmentStatus,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.Note,
		&i.NoteAttributes,
		&i.Tags,
		&i.SourceName,
		&i.SourceIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
		&i.CancelledAt,
		&i.ClosedAt,
	)
	return i, err
}

const createOrderLineItem = `-- name: CreateOrderLineItem :one
INSERT INTO order_line_items (
    order_id, shop_id, product_id, variant_id,
    title, variant_title, sku, quantity, fulfillable_quantity,
    unit_price_cents, discount_cents, total_cents,
    taxable, tax_lines, requires_shipping, properties
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, order_id, shop_id, product_id, variant_id, title, variant_title, sku, quantity, fulfillable_quantity, fulfilled_quantity, unit_price_cents, discount_cents, total_cents, taxable, tax_lines, requires_shipping, properties, created_at
`

type CreateOrderLineItemParams struct {
	OrderID          uuid.UUID   `json:"order_id"`
	ShopID           uuid.UUID   `json:"shop_id"`
	ProductID        pgtype.UUID `json:"product_id"`
	VariantID        pgtype.UUID `json:"variant_id"`
	Title            string      `json:"title"`
	VariantTitle     pgtype.Text `json:"variant_title"`
	Sku              pgtype.Text `json:"sku"`
	Quantity         int32       `json:"quantity"`
	UnitPriceCents   int64       `json:"unit_price_cents"`
	DiscountCents    int64       `json:"discount_cents"`
	TotalCents       int64       `json:"total_cents"`
	Taxable          bool        `json:"taxable"`
	TaxLines         []byte      `json:"tax_lines"`
	RequiresShipping bool        `json:"requires_shipping"`
	Properties       []byte      `json:"properties"`
}

func (q *Queries) CreateOrderLineItem(ctx context.Context, arg CreateOrderLineItemParams) (OrderLineItem, error) {
	row := q.db.QueryRow(ctx, createOrderLineItem,
		arg.OrderID,
		arg.ShopID,
		arg.ProductID,
		arg.VariantID,
		arg.Title,
		arg.VariantTitle,
		arg.Sku,
		arg.Quantity,
		arg.UnitPriceCents,
		arg.DiscountCents,
		arg.TotalCents,
		arg.Taxable,
		arg.TaxLines,
		arg.RequiresShipping,
		arg.Properties,
	)
	var i OrderLineItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ShopID,
		&i.ProductID,
		&i.VariantID,
		&i.Title,
		&i.VariantTitle,
		&i.Sku,
		&i.Quantity,
		&i.FulfillableQuantity,
		&i.FulfilledQuantity,
		&i.UnitPriceCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.Taxable,
		&i.TaxLines,
		&i.RequiresShipping,
		&i.Properties,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, shop_id, organization_id, customer_id, order_number, email, phone, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, refunded_cents, status, financial_status, fulfillment_status, shipping_address, billing_address, note, note_attributes, tags, source_name, source_identifier, created_at, updated_at, processed_at, cancelled_at, closed_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Email,
		&i.Phone,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.RefundedCents,
		&i.Status,
		&i.FinancialStatus,
		&i.FulfillmentStatus,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.Note,
		&i.NoteAttributes,
		&i.Tags,
		&i.SourceName,
		&i.SourceIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
		&i.CancelledAt,
		&i.ClosedAt,
	)
	return i, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, shop_id, organization_id, customer_id, order_number, email, phone, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, refunded_cents, status, financial_status, fulfillment_status, shipping_address, billing_address, note, note_attributes, tags, source_name, source_identifier, created_at, updated_at, processed_at, cancelled_at, closed_at FROM orders WHERE shop_id = $1 AND order_number = $2
`

type GetOrderByNumberParams struct {
	ShopID      uuid.UUID `json:"shop_id"`
	OrderNumber int64     `json:"order_number"`
}

func (q *Queries) GetOrderByNumber(ctx context.Context, arg GetOrderByNumberParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByNumber, arg.ShopID, arg.OrderNumber)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Email,
		&i.Phone,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.RefundedCents,
		&i.Status,
		&i.FinancialStatus,
		&i.FulfillmentStatus,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.Note,
		&i.NoteAttributes,
		&i.Tags,
		&i.SourceName,
		&i.SourceIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
		&i.CancelledAt,
		&i.ClosedAt,
	)
	return i, err
}

const getOrderLineItems = `-- name: GetOrderLineItems :many
SELECT id, order_id, shop_id, product_id, variant_id, title, variant_title, sku, quantity, fulfillable_quantity, fulfilled_quantity, unit_price_cents, discount_cents, total_cents, taxable, tax_lines, requires_shipping, properties, created_at FROM order_line_items WHERE order_id = $1
`

func (q *Queries) GetOrderLineItems(ctx context.Context, orderID uuid.UUID) ([]OrderLineItem, error) {
	rows, err := q.db.Query(ctx, getOrderLineItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderLineItem{}
	for rows.Next() {
		var i OrderLineItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ShopID,
			&i.ProductID,
			&i.VariantID,
			&i.Title,
			&i.VariantTitle,
			&i.Sku,
			&i.Quantity,
			&i.FulfillableQuantity,
			&i.FulfilledQuantity,
			&i.UnitPriceCents,
			&i.DiscountCents,
			&i.TotalCents,
			&i.Taxable,
			&i.TaxLines,
			&i.RequiresShipping,
			&i.Properties,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderTotalsByShop = `-- name: GetOrderTotalsByShop :one
SELECT 
    COUNT(*) as order_count,
    COALESCE(SUM(total_cents), 0) as total_revenue_cents,
    COALESCE(AVG(total_cents), 0) as average_order_cents
FROM orders
WHERE shop_id = $1 AND status != 'cancelled'
`

type GetOrderTotalsByShopRow struct {
	OrderCount        int64       `json:"order_count"`
	TotalRevenueCents interface{} `json:"total_revenue_cents"`
	AverageOrderCents interface{} `json:"average_order_cents"`
}

func (q *Queries) GetOrderTotalsByShop(ctx context.Context, shopID uuid.UUID) (GetOrderTotalsByShopRow, error) {
	row := q.db.QueryRow(ctx, getOrderTotalsByShop, shopID)
	var i GetOrderTotalsByShopRow
	err := row.Scan(&i.OrderCount, &i.TotalRevenueCents, &i.AverageOrderCents)
	return i, err
}

const getOrderWithLineItems = `-- name: GetOrderWithLineItems :many
SELECT 
    o.id, o.shop_id, o.organization_id, o.customer_id, o.order_number, o.email, o.phone, o.currency, o.subtotal_cents, o.discount_cents, o.shipping_cents, o.tax_cents, o.total_cents, o.refunded_cents, o.status, o.financial_status, o.fulfillment_status, o.shipping_address, o.billing_address, o.note, o.note_attributes, o.tags, o.source_name, o.source_identifier, o.created_at, o.updated_at, o.processed_at, o.cancelled_at, o.closed_at,
    COALESCE(
        json_agg(
            json_build_object(
                'id', li.id,
                'title', li.title,
                'variant_title', li.variant_title,
                'sku', li.sku,
                'quantity', li.quantity,
                'fulfilled_quantity', li.fulfilled_quantity,
                'unit_price_cents', li.unit_price_cents,
                'discount_cents', li.discount_cents,
                'total_cents', li.total_cents
            )
        ) FILTER (WHERE li.id IS NOT NULL),
        '[]'
    ) as line_items
FROM orders o
LEFT JOIN order_line_items li ON li.order_id = o.id
WHERE o.id = $1
GROUP BY o.id
`

type GetOrderWithLineItemsRow struct {
	ID                uuid.UUID          `json:"id"`
	ShopID            uuid.UUID          `json:"shop_id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	OrderNumber       int64              `json:"order_number"`
	Email             string             `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	Currency          string             `json:"currency"`
	SubtotalCents     int64              `json:"subtotal_cents"`
	DiscountCents     int64              `json:"discount_cents"`
	ShippingCents     int64              `json:"shipping_cents"`
	TaxCents          int64              `json:"tax_cents"`
	TotalCents        int64              `json:"total_cents"`
	RefundedCents     int64              `json:"refunded_cents"`
	Status            string             `json:"status"`
	FinancialStatus   string             `json:"financial_status"`
	FulfillmentStatus pgtype.Text        `json:"fulfillment_status"`
	ShippingAddress   []byte             `json:"shipping_address"`
	BillingAddress    []byte             `json:"billing_address"`
	Note              pgtype.Text        `json:"note"`
	NoteAttributes    []byte             `json:"note_attributes"`
	Tags              []string           `json:"tags"`
	SourceName        string             `json:"source_name"`
	SourceIdentifier  pgtype.Text        `json:"source_identifier"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	ProcessedAt       pgtype.Timestamptz `json:"processed_at"`
	CancelledAt       pgtype.Timestamptz `json:"cancelled_at"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
	LineItems         interface{}        `json:"line_items"`
}

func (q *Queries) GetOrderWithLineItems(ctx context.Context, id uuid.UUID) ([]GetOrderWithLineItemsRow, error) {
	rows, err := q.db.Query(ctx, getOrderWithLineItems, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderWithLineItemsRow{}
	for rows.Next() {
		var i GetOrderWithLineItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.OrganizationID,
			&i.CustomerID,
			&i.OrderNumber,
			&i.Email,
			&i.Phone,
			&i.Currency,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.ShippingCents,
			&i.TaxCents,
			&i.TotalCents,
			&i.RefundedCents,
			&i.Status,
			&i.FinancialStatus,
			&i.FulfillmentStatus,
			&i.ShippingAddress,
			&i.BillingAddress,
			&i.Note,
			&i.NoteAttributes,
			&i.Tags,
			&i.SourceName,
			&i.SourceIdentifier,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessedAt,
			&i.CancelledAt,
			&i.ClosedAt,
			&i.LineItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCustomer = `-- name: ListOrdersByCustomer :many
SELECT id, shop_id, organization_id, customer_id, order_number, email, phone, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, refunded_cents, status, financial_status, fulfillment_status, shipping_address, billing_address, note, note_attributes, tags, source_name, source_identifier, created_at, updated_at, processed_at, cancelled_at, closed_at FROM orders
WHERE customer_id = $1
  AND ($2::TIMESTAMPTZ IS NULL OR created_at < $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListOrdersByCustomerParams struct {
	CustomerID pgtype.UUID        `json:"customer_id"`
	Cursor     pgtype.Timestamptz `json:"cursor"`
	Limit      int32              `json:"limit"`
}

func (q *Queries) ListOrdersByCustomer(ctx context.Context, arg ListOrdersByCustomerParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomer, arg.CustomerID, arg.Cursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.OrganizationID,
			&i.CustomerID,
			&i.OrderNumber,
			&i.Email,
			&i.Phone,
			&i.Currency,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.ShippingCents,
			&i.TaxCents,
			&i.TotalCents,
			&i.RefundedCents,
			&i.Status,
			&i.FinancialStatus,
			&i.FulfillmentStatus,
			&i.ShippingAddress,
			&i.BillingAddress,
			&i.Note,
			&i.NoteAttributes,
			&i.Tags,
			&i.SourceName,
			&i.SourceIdentifier,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessedAt,
			&i.CancelledAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByOrganization = `-- name: ListOrdersByOrganization :many
SELECT id, shop_id, organization_id, customer_id, order_number, email, phone, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, refunded_cents, status, financial_status, fulfillment_status, shipping_address, billing_address, note, note_attributes, tags, source_name, source_identifier, created_at, updated_at, processed_at, cancelled_at, closed_at FROM orders
WHERE organization_id = $1
  AND ($2::TEXT IS NULL OR status = $2)
  AND ($3::TIMESTAMPTZ IS NULL OR created_at < $3)
ORDER BY created_at DESC
LIMIT $4
`

type ListOrdersByOrganizationParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	Status         pgtype.Text        `json:"status"`
	Cursor         pgtype.Timestamptz `json:"cursor"`
	Limit          int32              `json:"limit"`
}

func (q *Queries) ListOrdersByOrganization(ctx context.Context, arg ListOrdersByOrganizationParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByOrganization,
		arg.OrganizationID,
		arg.Status,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.OrganizationID,
			&i.CustomerID,
			&i.OrderNumber,
			&i.Email,
			&i.Phone,
			&i.Currency,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.ShippingCents,
			&i.TaxCents,
			&i.TotalCents,
			&i.RefundedCents,
			&i.Status,
			&i.FinancialStatus,
			&i.FulfillmentStatus,
			&i.ShippingAddress,
			&i.BillingAddress,
			&i.Note,
			&i.NoteAttributes,
			&i.Tags,
			&i.SourceName,
			&i.SourceIdentifier,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessedAt,
			&i.CancelledAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByShop = `-- name: ListOrdersByShop :many
SELECT id, shop_id, organization_id, customer_id, order_number, email, phone, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, refunded_cents, status, financial_status, fulfillment_status, shipping_address, billing_address, note, note_attributes, tags, source_name, source_identifier, created_at, updated_at, processed_at, cancelled_at, closed_at FROM orders
WHERE shop_id = $1
  AND ($2::TEXT IS NULL OR status = $2)
  AND ($3::TEXT IS NULL OR financial_status = $3)
  AND ($4::TEXT IS NULL OR fulfillment_status = $4)
  AND ($5::TIMESTAMPTZ IS NULL OR created_at < $5)
ORDER BY created_at DESC
LIMIT $6
`

type ListOrdersByShopParams struct {
	ShopID            uuid.UUID          `json:"shop_id"`
	Status            pgtype.Text        `json:"status"`
	FinancialStatus   pgtype.Text        `json:"financial_status"`
	FulfillmentStatus pgtype.Text        `json:"fulfillment_status"`
	Cursor            pgtype.Timestamptz `json:"cursor"`
	Limit             int32              `json:"limit"`
}

func (q *Queries) ListOrdersByShop(ctx context.Context, arg ListOrdersByShopParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByShop,
		arg.ShopID,
		arg.Status,
		arg.FinancialStatus,
		arg.FulfillmentStatus,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.OrganizationID,
			&i.CustomerID,
			&i.OrderNumber,
			&i.Email,
			&i.Phone,
			&i.Currency,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.ShippingCents,
			&i.TaxCents,
			&i.TotalCents,
			&i.RefundedCents,
			&i.Status,
			&i.FinancialStatus,
			&i.FulfillmentStatus,
			&i.ShippingAddress,
			&i.BillingAddress,
			&i.Note,
			&i.NoteAttributes,
			&i.Tags,
			&i.SourceName,
			&i.SourceIdentifier,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessedAt,
			&i.CancelledAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLineItemFulfillment = `-- name: UpdateLineItemFulfillment :one
UPDATE order_line_items
SET 
    fulfilled_quantity = fulfilled_quantity + $2,
    fulfillable_quantity = fulfillable_quantity - $2
WHERE id = $1 AND fulfillable_quantity >= $2
RETURNING id, order_id, shop_id, product_id, variant_id, title, variant_title, sku, quantity, fulfillable_quantity, fulfilled_quantity, unit_price_cents, discount_cents, total_cents, taxable, tax_lines, requires_shipping, properties, created_at
`

type UpdateLineItemFulfillmentParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) UpdateLineItemFulfillment(ctx context.Context, arg UpdateLineItemFulfillmentParams) (OrderLineItem, error) {
	row := q.db.QueryRow(ctx, updateLineItemFulfillment, arg.ID, arg.Quantity)
	var i OrderLineItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ShopID,
		&i.ProductID,
		&i.VariantID,
		&i.Title,
		&i.VariantTitle,
		&i.Sku,
		&i.Quantity,
		&i.FulfillableQuantity,
		&i.FulfilledQuantity,
		&i.UnitPriceCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.Taxable,
		&i.TaxLines,
		&i.RequiresShipping,
		&i.Properties,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrderRefund = `-- name: UpdateOrderRefund :one
UPDATE orders
SET 
    refunded_cents = refunded_cents + $2,
    financial_status = CASE 
        WHEN refunded_cents + $2 >= total_cents THEN 'refunded'
        ELSE 'partially_refunded'
    END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, shop_id, organization_id, customer_id, order_number, email, phone, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, refunded_cents, status, financial_status, fulfillment_status, shipping_address, billing_address, note, note_attributes, tags, source_name, source_identifier, created_at, updated_at, processed_at, cancelled_at, closed_at
`

type UpdateOrderRefundParams struct {
	ID           uuid.UUID `json:"id"`
	RefundAmount int64     `json:"refund_amount"`
}

func (q *Queries) UpdateOrderRefund(ctx context.Context, arg UpdateOrderRefundParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderRefund, arg.ID, arg.RefundAmount)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Email,
		&i.Phone,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.RefundedCents,
		&i.Status,
		&i.FinancialStatus,
		&i.FulfillmentStatus,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.Note,
		&i.NoteAttributes,
		&i.Tags,
		&i.SourceName,
		&i.SourceIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
		&i.CancelledAt,
		&i.ClosedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET 
    status = COALESCE($2, status),
    financial_status = COALESCE($3, financial_status),
    fulfillment_status = COALESCE($4, fulfillment_status),
    updated_at = NOW()
WHERE id = $1
RETURNING id, shop_id, organization_id, customer_id, order_number, email, phone, currency, subtotal_cents, discount_cents, shipping_cents, tax_cents, total_cents, refunded_cents, status, financial_status, fulfillment_status, shipping_address, billing_address, note, note_attributes, tags, source_name, source_identifier, created_at, updated_at, processed_at, cancelled_at, closed_at
`

type UpdateOrderStatusParams struct {
	ID                uuid.UUID   `json:"id"`
	Status            pgtype.Text `json:"status"`
	FinancialStatus   pgtype.Text `json:"financial_status"`
	FulfillmentStatus pgtype.Text `json:"fulfillment_status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus,
		arg.ID,
		arg.Status,
		arg.FinancialStatus,
		arg.FulfillmentStatus,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Email,
		&i.Phone,
		&i.Currency,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.RefundedCents,
		&i.Status,
		&i.FinancialStatus,
		&i.FulfillmentStatus,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.Note,
		&i.NoteAttributes,
		&i.Tags,
		&i.SourceName,
		&i.SourceIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
		&i.CancelledAt,
		&i.ClosedAt,
	)
	return i, err
}
