// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: organizations.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptOrganizationInvite = `-- name: AcceptOrganizationInvite :one
UPDATE organization_members
SET accepted_at = NOW(), updated_at = NOW()
WHERE organization_id = $1 AND user_id = $2
RETURNING id, organization_id, user_id, role, invited_by, invited_at, accepted_at, created_at, updated_at
`

type AcceptOrganizationInviteParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) AcceptOrganizationInvite(ctx context.Context, arg AcceptOrganizationInviteParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, acceptOrganizationInvite, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addOrganizationMember = `-- name: AddOrganizationMember :one

INSERT INTO organization_members (
    organization_id, user_id, role, invited_by, invited_at
)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, organization_id, user_id, role, invited_by, invited_at, accepted_at, created_at, updated_at
`

type AddOrganizationMemberParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	UserID         uuid.UUID   `json:"user_id"`
	Role           string      `json:"role"`
	InvitedBy      pgtype.UUID `json:"invited_by"`
}

// =============================================================================
// ORGANIZATION MEMBERS
// =============================================================================
func (q *Queries) AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, addOrganizationMember,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
	)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOrganizationMembers = `-- name: CountOrganizationMembers :one
SELECT COUNT(*) FROM organization_members WHERE organization_id = $1
`

func (q *Queries) CountOrganizationMembers(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationMembers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizations = `-- name: CountOrganizations :one
SELECT COUNT(*) FROM organizations WHERE deleted_at IS NULL
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one

INSERT INTO organizations (
    name, handle, plan, billing_email, stripe_customer_id,
    status, max_shops, max_members, settings
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, handle, plan, billing_email, stripe_customer_id, status, max_shops, max_members, settings, created_at, updated_at, deleted_at
`

type CreateOrganizationParams struct {
	Name             string          `json:"name"`
	Handle           string          `json:"handle"`
	Plan             string          `json:"plan"`
	BillingEmail     pgtype.Text     `json:"billing_email"`
	StripeCustomerID pgtype.Text     `json:"stripe_customer_id"`
	Status           string          `json:"status"`
	MaxShops         int32           `json:"max_shops"`
	MaxMembers       int32           `json:"max_members"`
	Settings         json.RawMessage `json:"settings"`
}

// db/queries/organizations.sql
func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Handle,
		arg.Plan,
		arg.BillingEmail,
		arg.StripeCustomerID,
		arg.Status,
		arg.MaxShops,
		arg.MaxMembers,
		arg.Settings,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Plan,
		&i.BillingEmail,
		&i.StripeCustomerID,
		&i.Status,
		&i.MaxShops,
		&i.MaxMembers,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationByHandle = `-- name: GetOrganizationByHandle :one
SELECT id, name, handle, plan, billing_email, stripe_customer_id, status, max_shops, max_members, settings, created_at, updated_at, deleted_at FROM organizations WHERE handle = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByHandle(ctx context.Context, handle string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByHandle, handle)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Plan,
		&i.BillingEmail,
		&i.StripeCustomerID,
		&i.Status,
		&i.MaxShops,
		&i.MaxMembers,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, handle, plan, billing_email, stripe_customer_id, status, max_shops, max_members, settings, created_at, updated_at, deleted_at FROM organizations WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Plan,
		&i.BillingEmail,
		&i.StripeCustomerID,
		&i.Status,
		&i.MaxShops,
		&i.MaxMembers,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationByStripeCustomer = `-- name: GetOrganizationByStripeCustomer :one
SELECT id, name, handle, plan, billing_email, stripe_customer_id, status, max_shops, max_members, settings, created_at, updated_at, deleted_at FROM organizations WHERE stripe_customer_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByStripeCustomer(ctx context.Context, stripeCustomerID pgtype.Text) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByStripeCustomer, stripeCustomerID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Plan,
		&i.BillingEmail,
		&i.StripeCustomerID,
		&i.Status,
		&i.MaxShops,
		&i.MaxMembers,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationMember = `-- name: GetOrganizationMember :one
SELECT id, organization_id, user_id, role, invited_by, invited_at, accepted_at, created_at, updated_at FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type GetOrganizationMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOrganizationMember(ctx context.Context, arg GetOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMember, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isOrganizationAdmin = `-- name: IsOrganizationAdmin :one
SELECT EXISTS(
    SELECT 1 FROM organization_members 
    WHERE organization_id = $1 AND user_id = $2 AND role IN ('owner', 'admin')
)
`

type IsOrganizationAdminParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) IsOrganizationAdmin(ctx context.Context, arg IsOrganizationAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOrganizationAdmin, arg.OrganizationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isOrganizationOwner = `-- name: IsOrganizationOwner :one
SELECT EXISTS(
    SELECT 1 FROM organization_members 
    WHERE organization_id = $1 AND user_id = $2 AND role = 'owner'
)
`

type IsOrganizationOwnerParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) IsOrganizationOwner(ctx context.Context, arg IsOrganizationOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOrganizationOwner, arg.OrganizationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT 
    om.id, om.organization_id, om.user_id, om.role, om.invited_by, om.invited_at, om.accepted_at, om.created_at, om.updated_at,
    u.email,
    u.first_name,
    u.last_name,
    u.avatar_url
FROM organization_members om
JOIN users u ON u.id = om.user_id
WHERE om.organization_id = $1
ORDER BY om.created_at DESC
`

type ListOrganizationMembersRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Role           string             `json:"role"`
	InvitedBy      pgtype.UUID        `json:"invited_by"`
	InvitedAt      pgtype.Timestamptz `json:"invited_at"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	Email          string             `json:"email"`
	FirstName      pgtype.Text        `json:"first_name"`
	LastName       pgtype.Text        `json:"last_name"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.InvitedAt,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, handle, plan, billing_email, stripe_customer_id, status, max_shops, max_members, settings, created_at, updated_at, deleted_at FROM organizations
WHERE deleted_at IS NULL
  AND ($1::TEXT IS NULL OR status = $1)
  AND ($2::TIMESTAMPTZ IS NULL OR created_at < $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListOrganizationsParams struct {
	Status pgtype.Text        `json:"status"`
	Cursor pgtype.Timestamptz `json:"cursor"`
	Limit  int32              `json:"limit"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Status, arg.Cursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handle,
			&i.Plan,
			&i.BillingEmail,
			&i.StripeCustomerID,
			&i.Status,
			&i.MaxShops,
			&i.MaxMembers,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrganizations = `-- name: ListUserOrganizations :many
SELECT 
    o.id, o.name, o.handle, o.plan, o.billing_email, o.stripe_customer_id, o.status, o.max_shops, o.max_members, o.settings, o.created_at, o.updated_at, o.deleted_at,
    om.role
FROM organizations o
JOIN organization_members om ON om.organization_id = o.id
WHERE om.user_id = $1 AND o.deleted_at IS NULL
ORDER BY o.created_at DESC
`

type ListUserOrganizationsRow struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	Handle           string             `json:"handle"`
	Plan             string             `json:"plan"`
	BillingEmail     pgtype.Text        `json:"billing_email"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
	Status           string             `json:"status"`
	MaxShops         int32              `json:"max_shops"`
	MaxMembers       int32              `json:"max_members"`
	Settings         json.RawMessage    `json:"settings"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	Role             string             `json:"role"`
}

func (q *Queries) ListUserOrganizations(ctx context.Context, userID uuid.UUID) ([]ListUserOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserOrganizationsRow{}
	for rows.Next() {
		var i ListUserOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handle,
			&i.Plan,
			&i.BillingEmail,
			&i.StripeCustomerID,
			&i.Status,
			&i.MaxShops,
			&i.MaxMembers,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organizationExistsByHandle = `-- name: OrganizationExistsByHandle :one
SELECT EXISTS(SELECT 1 FROM organizations WHERE handle = $1 AND deleted_at IS NULL)
`

func (q *Queries) OrganizationExistsByHandle(ctx context.Context, handle string) (bool, error) {
	row := q.db.QueryRow(ctx, organizationExistsByHandle, handle)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeOrganizationMember = `-- name: RemoveOrganizationMember :exec
DELETE FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type RemoveOrganizationMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveOrganizationMember(ctx context.Context, arg RemoveOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, removeOrganizationMember, arg.OrganizationID, arg.UserID)
	return err
}

const setStripeCustomerID = `-- name: SetStripeCustomerID :one
UPDATE organizations
SET stripe_customer_id = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, handle, plan, billing_email, stripe_customer_id, status, max_shops, max_members, settings, created_at, updated_at, deleted_at
`

type SetStripeCustomerIDParams struct {
	ID               uuid.UUID   `json:"id"`
	StripeCustomerID pgtype.Text `json:"stripe_customer_id"`
}

func (q *Queries) SetStripeCustomerID(ctx context.Context, arg SetStripeCustomerIDParams) (Organization, error) {
	row := q.db.QueryRow(ctx, setStripeCustomerID, arg.ID, arg.StripeCustomerID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Plan,
		&i.BillingEmail,
		&i.StripeCustomerID,
		&i.Status,
		&i.MaxShops,
		&i.MaxMembers,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteOrganization = `-- name: SoftDeleteOrganization :exec
UPDATE organizations SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteOrganization, id)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET
    name = COALESCE($2, name),
    handle = COALESCE($3, handle),
    billing_email = COALESCE($4, billing_email),
    settings = COALESCE($5, settings),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, handle, plan, billing_email, stripe_customer_id, status, max_shops, max_members, settings, created_at, updated_at, deleted_at
`

type UpdateOrganizationParams struct {
	ID           uuid.UUID   `json:"id"`
	Name         pgtype.Text `json:"name"`
	Handle       pgtype.Text `json:"handle"`
	BillingEmail pgtype.Text `json:"billing_email"`
	Settings     []byte      `json:"settings"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Handle,
		arg.BillingEmail,
		arg.Settings,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Plan,
		&i.BillingEmail,
		&i.StripeCustomerID,
		&i.Status,
		&i.MaxShops,
		&i.MaxMembers,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateOrganizationMemberRole = `-- name: UpdateOrganizationMemberRole :one
UPDATE organization_members
SET role = $3, updated_at = NOW()
WHERE organization_id = $1 AND user_id = $2
RETURNING id, organization_id, user_id, role, invited_by, invited_at, accepted_at, created_at, updated_at
`

type UpdateOrganizationMemberRoleParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) UpdateOrganizationMemberRole(ctx context.Context, arg UpdateOrganizationMemberRoleParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMemberRole, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationPlan = `-- name: UpdateOrganizationPlan :one
UPDATE organizations
SET 
    plan = $2,
    max_shops = $3,
    max_members = $4,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, handle, plan, billing_email, stripe_customer_id, status, max_shops, max_members, settings, created_at, updated_at, deleted_at
`

type UpdateOrganizationPlanParams struct {
	ID         uuid.UUID `json:"id"`
	Plan       string    `json:"plan"`
	MaxShops   int32     `json:"max_shops"`
	MaxMembers int32     `json:"max_members"`
}

func (q *Queries) UpdateOrganizationPlan(ctx context.Context, arg UpdateOrganizationPlanParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationPlan,
		arg.ID,
		arg.Plan,
		arg.MaxShops,
		arg.MaxMembers,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Plan,
		&i.BillingEmail,
		&i.StripeCustomerID,
		&i.Status,
		&i.MaxShops,
		&i.MaxMembers,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateOrganizationStatus = `-- name: UpdateOrganizationStatus :one
UPDATE organizations
SET status = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, handle, plan, billing_email, stripe_customer_id, status, max_shops, max_members, settings, created_at, updated_at, deleted_at
`

type UpdateOrganizationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrganizationStatus(ctx context.Context, arg UpdateOrganizationStatusParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationStatus, arg.ID, arg.Status)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Plan,
		&i.BillingEmail,
		&i.StripeCustomerID,
		&i.Status,
		&i.MaxShops,
		&i.MaxMembers,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
