// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addInventory = `-- name: AddInventory :one
UPDATE products
SET inventory_quantity = inventory_quantity + $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, shop_id, organization_id, title, description, description_html, handle, price_cents, compare_at_price_cents, cost_cents, vendor, product_type, tags, sku, barcode, inventory_quantity, track_inventory, status, seo_title, seo_description, template_suffix, created_at, updated_at, published_at, deleted_at
`

type AddInventoryParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) AddInventory(ctx context.Context, arg AddInventoryParams) (Product, error) {
	row := q.db.QueryRow(ctx, addInventory, arg.ID, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Title,
		&i.Description,
		&i.DescriptionHtml,
		&i.Handle,
		&i.PriceCents,
		&i.CompareAtPriceCents,
		&i.CostCents,
		&i.Vendor,
		&i.ProductType,
		&i.Tags,
		&i.Sku,
		&i.Barcode,
		&i.InventoryQuantity,
		&i.TrackInventory,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.TemplateSuffix,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const archiveProduct = `-- name: ArchiveProduct :one
UPDATE products
SET status = 'archived', updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, shop_id, organization_id, title, description, description_html, handle, price_cents, compare_at_price_cents, cost_cents, vendor, product_type, tags, sku, barcode, inventory_quantity, track_inventory, status, seo_title, seo_description, template_suffix, created_at, updated_at, published_at, deleted_at
`

func (q *Queries) ArchiveProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, archiveProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Title,
		&i.Description,
		&i.DescriptionHtml,
		&i.Handle,
		&i.PriceCents,
		&i.CompareAtPriceCents,
		&i.CostCents,
		&i.Vendor,
		&i.ProductType,
		&i.Tags,
		&i.Sku,
		&i.Barcode,
		&i.InventoryQuantity,
		&i.TrackInventory,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.TemplateSuffix,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countProductsByOrganization = `-- name: CountProductsByOrganization :one
SELECT COUNT(*) FROM products
WHERE organization_id = $1 AND deleted_at IS NULL
  AND ($2::TEXT IS NULL OR status = $2)
`

type CountProductsByOrganizationParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Status         pgtype.Text `json:"status"`
}

func (q *Queries) CountProductsByOrganization(ctx context.Context, arg CountProductsByOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByOrganization, arg.OrganizationID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByShop = `-- name: CountProductsByShop :one
SELECT COUNT(*) FROM products
WHERE shop_id = $1 AND deleted_at IS NULL
  AND ($2::TEXT IS NULL OR status = $2)
`

type CountProductsByShopParams struct {
	ShopID uuid.UUID   `json:"shop_id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) CountProductsByShop(ctx context.Context, arg CountProductsByShopParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByShop, arg.ShopID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one

INSERT INTO products (
    shop_id, organization_id, title, description, description_html, handle,
    price_cents, compare_at_price_cents, cost_cents,
    vendor, product_type, tags,
    sku, barcode, inventory_quantity, track_inventory,
    status, seo_title, seo_description, template_suffix
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
RETURNING id, shop_id, organization_id, title, description, description_html, handle, price_cents, compare_at_price_cents, cost_cents, vendor, product_type, tags, sku, barcode, inventory_quantity, track_inventory, status, seo_title, seo_description, template_suffix, created_at, updated_at, published_at, deleted_at
`

type CreateProductParams struct {
	ShopID              uuid.UUID   `json:"shop_id"`
	OrganizationID      uuid.UUID   `json:"organization_id"`
	Title               string      `json:"title"`
	Description         pgtype.Text `json:"description"`
	DescriptionHtml     pgtype.Text `json:"description_html"`
	Handle              string      `json:"handle"`
	PriceCents          int64       `json:"price_cents"`
	CompareAtPriceCents pgtype.Int8 `json:"compare_at_price_cents"`
	CostCents           pgtype.Int8 `json:"cost_cents"`
	Vendor              pgtype.Text `json:"vendor"`
	ProductType         pgtype.Text `json:"product_type"`
	Tags                []string    `json:"tags"`
	Sku                 pgtype.Text `json:"sku"`
	Barcode             pgtype.Text `json:"barcode"`
	InventoryQuantity   int32       `json:"inventory_quantity"`
	TrackInventory      bool        `json:"track_inventory"`
	Status              string      `json:"status"`
	SeoTitle            pgtype.Text `json:"seo_title"`
	SeoDescription      pgtype.Text `json:"seo_description"`
	TemplateSuffix      pgtype.Text `json:"template_suffix"`
}

// db/queries/products.sql
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ShopID,
		arg.OrganizationID,
		arg.Title,
		arg.Description,
		arg.DescriptionHtml,
		arg.Handle,
		arg.PriceCents,
		arg.CompareAtPriceCents,
		arg.CostCents,
		arg.Vendor,
		arg.ProductType,
		arg.Tags,
		arg.Sku,
		arg.Barcode,
		arg.InventoryQuantity,
		arg.TrackInventory,
		arg.Status,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.TemplateSuffix,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Title,
		&i.Description,
		&i.DescriptionHtml,
		&i.Handle,
		&i.PriceCents,
		&i.CompareAtPriceCents,
		&i.CostCents,
		&i.Vendor,
		&i.ProductType,
		&i.Tags,
		&i.Sku,
		&i.Barcode,
		&i.InventoryQuantity,
		&i.TrackInventory,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.TemplateSuffix,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deductInventory = `-- name: DeductInventory :one
UPDATE products
SET inventory_quantity = inventory_quantity - $2, updated_at = NOW()
WHERE id = $1 
  AND deleted_at IS NULL
  AND inventory_quantity >= $2
RETURNING id, shop_id, organization_id, title, description, description_html, handle, price_cents, compare_at_price_cents, cost_cents, vendor, product_type, tags, sku, barcode, inventory_quantity, track_inventory, status, seo_title, seo_description, template_suffix, created_at, updated_at, published_at, deleted_at
`

type DeductInventoryParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) DeductInventory(ctx context.Context, arg DeductInventoryParams) (Product, error) {
	row := q.db.QueryRow(ctx, deductInventory, arg.ID, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Title,
		&i.Description,
		&i.DescriptionHtml,
		&i.Handle,
		&i.PriceCents,
		&i.CompareAtPriceCents,
		&i.CostCents,
		&i.Vendor,
		&i.ProductType,
		&i.Tags,
		&i.Sku,
		&i.Barcode,
		&i.InventoryQuantity,
		&i.TrackInventory,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.TemplateSuffix,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductByHandle = `-- name: GetProductByHandle :one
SELECT id, shop_id, organization_id, title, description, description_html, handle, price_cents, compare_at_price_cents, cost_cents, vendor, product_type, tags, sku, barcode, inventory_quantity, track_inventory, status, seo_title, seo_description, template_suffix, created_at, updated_at, published_at, deleted_at FROM products 
WHERE shop_id = $1 AND handle = $2 AND deleted_at IS NULL
`

type GetProductByHandleParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	Handle string    `json:"handle"`
}

func (q *Queries) GetProductByHandle(ctx context.Context, arg GetProductByHandleParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByHandle, arg.ShopID, arg.Handle)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Title,
		&i.Description,
		&i.DescriptionHtml,
		&i.Handle,
		&i.PriceCents,
		&i.CompareAtPriceCents,
		&i.CostCents,
		&i.Vendor,
		&i.ProductType,
		&i.Tags,
		&i.Sku,
		&i.Barcode,
		&i.InventoryQuantity,
		&i.TrackInventory,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.TemplateSuffix,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, shop_id, organization_id, title, description, description_html, handle, price_cents, compare_at_price_cents, cost_cents, vendor, product_type, tags, sku, barcode, inventory_quantity, track_inventory, status, seo_title, seo_description, template_suffix, created_at, updated_at, published_at, deleted_at FROM products 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Title,
		&i.Description,
		&i.DescriptionHtml,
		&i.Handle,
		&i.PriceCents,
		&i.CompareAtPriceCents,
		&i.CostCents,
		&i.Vendor,
		&i.ProductType,
		&i.Tags,
		&i.Sku,
		&i.Barcode,
		&i.InventoryQuantity,
		&i.TrackInventory,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.TemplateSuffix,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProductsByIDs = `-- name: ListProductsByIDs :many
SELECT id, shop_id, organization_id, title, description, description_html, handle, price_cents, compare_at_price_cents, cost_cents, vendor, product_type, tags, sku, barcode, inventory_quantity, track_inventory, status, seo_title, seo_description, template_suffix, created_at, updated_at, published_at, deleted_at FROM products
WHERE id = ANY($1::UUID[]) AND deleted_at IS NULL
`

func (q *Queries) ListProductsByIDs(ctx context.Context, ids []uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.OrganizationID,
			&i.Title,
			&i.Description,
			&i.DescriptionHtml,
			&i.Handle,
			&i.PriceCents,
			&i.CompareAtPriceCents,
			&i.CostCents,
			&i.Vendor,
			&i.ProductType,
			&i.Tags,
			&i.Sku,
			&i.Barcode,
			&i.InventoryQuantity,
			&i.TrackInventory,
			&i.Status,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.TemplateSuffix,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByOrganization = `-- name: ListProductsByOrganization :many
SELECT id, shop_id, organization_id, title, description, description_html, handle, price_cents, compare_at_price_cents, cost_cents, vendor, product_type, tags, sku, barcode, inventory_quantity, track_inventory, status, seo_title, seo_description, template_suffix, created_at, updated_at, published_at, deleted_at FROM products
WHERE organization_id = $1 AND deleted_at IS NULL
  AND ($2::TEXT IS NULL OR status = $2)
  AND ($3::TIMESTAMPTZ IS NULL OR created_at < $3)
ORDER BY created_at DESC
LIMIT $4
`

type ListProductsByOrganizationParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	Status         pgtype.Text        `json:"status"`
	Cursor         pgtype.Timestamptz `json:"cursor"`
	Limit          int32              `json:"limit"`
}

func (q *Queries) ListProductsByOrganization(ctx context.Context, arg ListProductsByOrganizationParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByOrganization,
		arg.OrganizationID,
		arg.Status,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.OrganizationID,
			&i.Title,
			&i.Description,
			&i.DescriptionHtml,
			&i.Handle,
			&i.PriceCents,
			&i.CompareAtPriceCents,
			&i.CostCents,
			&i.Vendor,
			&i.ProductType,
			&i.Tags,
			&i.Sku,
			&i.Barcode,
			&i.InventoryQuantity,
			&i.TrackInventory,
			&i.Status,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.TemplateSuffix,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByShop = `-- name: ListProductsByShop :many
SELECT id, shop_id, organization_id, title, description, description_html, handle, price_cents, compare_at_price_cents, cost_cents, vendor, product_type, tags, sku, barcode, inventory_quantity, track_inventory, status, seo_title, seo_description, template_suffix, created_at, updated_at, published_at, deleted_at FROM products
WHERE shop_id = $1 AND deleted_at IS NULL
  AND ($2::TEXT IS NULL OR status = $2)
  AND ($3::TIMESTAMPTZ IS NULL OR created_at < $3)
ORDER BY created_at DESC
LIMIT $4
`

type ListProductsByShopParams struct {
	ShopID uuid.UUID          `json:"shop_id"`
	Status pgtype.Text        `json:"status"`
	Cursor pgtype.Timestamptz `json:"cursor"`
	Limit  int32              `json:"limit"`
}

func (q *Queries) ListProductsByShop(ctx context.Context, arg ListProductsByShopParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByShop,
		arg.ShopID,
		arg.Status,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.OrganizationID,
			&i.Title,
			&i.Description,
			&i.DescriptionHtml,
			&i.Handle,
			&i.PriceCents,
			&i.CompareAtPriceCents,
			&i.CostCents,
			&i.Vendor,
			&i.ProductType,
			&i.Tags,
			&i.Sku,
			&i.Barcode,
			&i.InventoryQuantity,
			&i.TrackInventory,
			&i.Status,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.TemplateSuffix,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishProduct = `-- name: PublishProduct :one
UPDATE products
SET status = 'active', published_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, shop_id, organization_id, title, description, description_html, handle, price_cents, compare_at_price_cents, cost_cents, vendor, product_type, tags, sku, barcode, inventory_quantity, track_inventory, status, seo_title, seo_description, template_suffix, created_at, updated_at, published_at, deleted_at
`

func (q *Queries) PublishProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, publishProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Title,
		&i.Description,
		&i.DescriptionHtml,
		&i.Handle,
		&i.PriceCents,
		&i.CompareAtPriceCents,
		&i.CostCents,
		&i.Vendor,
		&i.ProductType,
		&i.Tags,
		&i.Sku,
		&i.Barcode,
		&i.InventoryQuantity,
		&i.TrackInventory,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.TemplateSuffix,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, shop_id, organization_id, title, description, description_html, handle, price_cents, compare_at_price_cents, cost_cents, vendor, product_type, tags, sku, barcode, inventory_quantity, track_inventory, status, seo_title, seo_description, template_suffix, created_at, updated_at, published_at, deleted_at FROM products
WHERE shop_id = $1 AND deleted_at IS NULL
  AND (title ILIKE '%' || $2 || '%' OR sku ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
LIMIT $3
`

type SearchProductsParams struct {
	ShopID uuid.UUID   `json:"shop_id"`
	Query  pgtype.Text `json:"query"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, searchProducts, arg.ShopID, arg.Query, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.OrganizationID,
			&i.Title,
			&i.Description,
			&i.DescriptionHtml,
			&i.Handle,
			&i.PriceCents,
			&i.CompareAtPriceCents,
			&i.CostCents,
			&i.Vendor,
			&i.ProductType,
			&i.Tags,
			&i.Sku,
			&i.Barcode,
			&i.InventoryQuantity,
			&i.TrackInventory,
			&i.Status,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.TemplateSuffix,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, id)
	return err
}

const unpublishProduct = `-- name: UnpublishProduct :one
UPDATE products
SET status = 'draft', published_at = NULL, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, shop_id, organization_id, title, description, description_html, handle, price_cents, compare_at_price_cents, cost_cents, vendor, product_type, tags, sku, barcode, inventory_quantity, track_inventory, status, seo_title, seo_description, template_suffix, created_at, updated_at, published_at, deleted_at
`

func (q *Queries) UnpublishProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, unpublishProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Title,
		&i.Description,
		&i.DescriptionHtml,
		&i.Handle,
		&i.PriceCents,
		&i.CompareAtPriceCents,
		&i.CostCents,
		&i.Vendor,
		&i.ProductType,
		&i.Tags,
		&i.Sku,
		&i.Barcode,
		&i.InventoryQuantity,
		&i.TrackInventory,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.TemplateSuffix,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    description_html = COALESCE($4, description_html),
    handle = COALESCE($5, handle),
    price_cents = COALESCE($6, price_cents),
    compare_at_price_cents = $7,
    cost_cents = $8,
    vendor = COALESCE($9, vendor),
    product_type = COALESCE($10, product_type),
    tags = COALESCE($11, tags),
    sku = COALESCE($12, sku),
    barcode = COALESCE($13, barcode),
    inventory_quantity = COALESCE($14, inventory_quantity),
    track_inventory = COALESCE($15, track_inventory),
    status = COALESCE($16, status),
    seo_title = COALESCE($17, seo_title),
    seo_description = COALESCE($18, seo_description),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, shop_id, organization_id, title, description, description_html, handle, price_cents, compare_at_price_cents, cost_cents, vendor, product_type, tags, sku, barcode, inventory_quantity, track_inventory, status, seo_title, seo_description, template_suffix, created_at, updated_at, published_at, deleted_at
`

type UpdateProductParams struct {
	ID                  uuid.UUID   `json:"id"`
	Title               pgtype.Text `json:"title"`
	Description         pgtype.Text `json:"description"`
	DescriptionHtml     pgtype.Text `json:"description_html"`
	Handle              pgtype.Text `json:"handle"`
	PriceCents          pgtype.Int8 `json:"price_cents"`
	CompareAtPriceCents pgtype.Int8 `json:"compare_at_price_cents"`
	CostCents           pgtype.Int8 `json:"cost_cents"`
	Vendor              pgtype.Text `json:"vendor"`
	ProductType         pgtype.Text `json:"product_type"`
	Tags                []string    `json:"tags"`
	Sku                 pgtype.Text `json:"sku"`
	Barcode             pgtype.Text `json:"barcode"`
	InventoryQuantity   pgtype.Int4 `json:"inventory_quantity"`
	TrackInventory      pgtype.Bool `json:"track_inventory"`
	Status              pgtype.Text `json:"status"`
	SeoTitle            pgtype.Text `json:"seo_title"`
	SeoDescription      pgtype.Text `json:"seo_description"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DescriptionHtml,
		arg.Handle,
		arg.PriceCents,
		arg.CompareAtPriceCents,
		arg.CostCents,
		arg.Vendor,
		arg.ProductType,
		arg.Tags,
		arg.Sku,
		arg.Barcode,
		arg.InventoryQuantity,
		arg.TrackInventory,
		arg.Status,
		arg.SeoTitle,
		arg.SeoDescription,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Title,
		&i.Description,
		&i.DescriptionHtml,
		&i.Handle,
		&i.PriceCents,
		&i.CompareAtPriceCents,
		&i.CostCents,
		&i.Vendor,
		&i.ProductType,
		&i.Tags,
		&i.Sku,
		&i.Barcode,
		&i.InventoryQuantity,
		&i.TrackInventory,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.TemplateSuffix,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProductStatus = `-- name: UpdateProductStatus :one
UPDATE products
SET status = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, shop_id, organization_id, title, description, description_html, handle, price_cents, compare_at_price_cents, cost_cents, vendor, product_type, tags, sku, barcode, inventory_quantity, track_inventory, status, seo_title, seo_description, template_suffix, created_at, updated_at, published_at, deleted_at
`

type UpdateProductStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStatus, arg.ID, arg.Status)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.OrganizationID,
		&i.Title,
		&i.Description,
		&i.DescriptionHtml,
		&i.Handle,
		&i.PriceCents,
		&i.CompareAtPriceCents,
		&i.CostCents,
		&i.Vendor,
		&i.ProductType,
		&i.Tags,
		&i.Sku,
		&i.Barcode,
		&i.InventoryQuantity,
		&i.TrackInventory,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.TemplateSuffix,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}
