// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptOrganizationInvite(ctx context.Context, arg AcceptOrganizationInviteParams) (OrganizationMember, error)
	AddInventory(ctx context.Context, arg AddInventoryParams) (Product, error)
	// =============================================================================
	// ORGANIZATION MEMBERS
	// =============================================================================
	AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) (OrganizationMember, error)
	ArchiveProduct(ctx context.Context, id uuid.UUID) (Product, error)
	CancelOrder(ctx context.Context, id uuid.UUID) (Order, error)
	ClearShopCustomDomain(ctx context.Context, id uuid.UUID) (Shop, error)
	CloseOrder(ctx context.Context, id uuid.UUID) (Order, error)
	ConfirmOrder(ctx context.Context, id uuid.UUID) (Order, error)
	CountCustomersByOrganization(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountCustomersByShop(ctx context.Context, shopID uuid.UUID) (int64, error)
	CountOrdersByCustomer(ctx context.Context, customerID pgtype.UUID) (int64, error)
	CountOrdersByShop(ctx context.Context, arg CountOrdersByShopParams) (int64, error)
	CountOrganizationMembers(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountOrganizations(ctx context.Context) (int64, error)
	CountProductsByOrganization(ctx context.Context, arg CountProductsByOrganizationParams) (int64, error)
	CountProductsByShop(ctx context.Context, arg CountProductsByShopParams) (int64, error)
	CountShopsByOrganization(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWebhookDeliveriesByStatus(ctx context.Context, arg CountWebhookDeliveriesByStatusParams) (int64, error)
	CountWebhookDeliveriesByWebhook(ctx context.Context, webhookID uuid.UUID) (int64, error)
	CountWebhooksByOrganization(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountWebhooksByShop(ctx context.Context, shopID pgtype.UUID) (int64, error)
	// db/queries/customers.sql
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	// db/queries/orders.sql
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderLineItem(ctx context.Context, arg CreateOrderLineItemParams) (OrderLineItem, error)
	// db/queries/organizations.sql
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	// db/queries/products.sql
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error)
	// db/queries/users.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error)
	DeductInventory(ctx context.Context, arg DeductInventoryParams) (Product, error)
	DeleteOldWebhookDeliveries(ctx context.Context, createdAt time.Time) error
	DeleteShop(ctx context.Context, id uuid.UUID) error
	DeleteWebhook(ctx context.Context, id uuid.UUID) error
	GetCustomerByEmail(ctx context.Context, arg GetCustomerByEmailParams) (Customer, error)
	GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderByNumber(ctx context.Context, arg GetOrderByNumberParams) (Order, error)
	GetOrderLineItems(ctx context.Context, orderID uuid.UUID) ([]OrderLineItem, error)
	GetOrderTotalsByShop(ctx context.Context, shopID uuid.UUID) (GetOrderTotalsByShopRow, error)
	GetOrderWithLineItems(ctx context.Context, id uuid.UUID) ([]GetOrderWithLineItemsRow, error)
	GetOrganizationByHandle(ctx context.Context, handle string) (Organization, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationByStripeCustomer(ctx context.Context, stripeCustomerID pgtype.Text) (Organization, error)
	GetOrganizationMember(ctx context.Context, arg GetOrganizationMemberParams) (OrganizationMember, error)
	GetProductByHandle(ctx context.Context, arg GetProductByHandleParams) (Product, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetShopByCustomDomain(ctx context.Context, customDomain pgtype.Text) (Shop, error)
	GetShopByGID(ctx context.Context, gid pgtype.Int8) (Shop, error)
	GetShopByHandle(ctx context.Context, arg GetShopByHandleParams) (Shop, error)
	GetShopByID(ctx context.Context, id uuid.UUID) (Shop, error)
	GetShopBySubdomain(ctx context.Context, subdomain string) (Shop, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWebhookByID(ctx context.Context, id uuid.UUID) (Webhook, error)
	GetWebhookByShopAndTopic(ctx context.Context, arg GetWebhookByShopAndTopicParams) (Webhook, error)
	GetWebhookDeliveryByID(ctx context.Context, id uuid.UUID) (WebhookDelivery, error)
	IncrementWebhookFailureCount(ctx context.Context, arg IncrementWebhookFailureCountParams) (Webhook, error)
	IsOrganizationAdmin(ctx context.Context, arg IsOrganizationAdminParams) (bool, error)
	IsOrganizationOwner(ctx context.Context, arg IsOrganizationOwnerParams) (bool, error)
	ListCustomersByOrganization(ctx context.Context, arg ListCustomersByOrganizationParams) ([]Customer, error)
	ListCustomersByShop(ctx context.Context, arg ListCustomersByShopParams) ([]Customer, error)
	ListOrdersByCustomer(ctx context.Context, arg ListOrdersByCustomerParams) ([]Order, error)
	ListOrdersByOrganization(ctx context.Context, arg ListOrdersByOrganizationParams) ([]Order, error)
	ListOrdersByShop(ctx context.Context, arg ListOrdersByShopParams) ([]Order, error)
	ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListPendingWebhookDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error)
	ListProductsByIDs(ctx context.Context, ids []uuid.UUID) ([]Product, error)
	ListProductsByOrganization(ctx context.Context, arg ListProductsByOrganizationParams) ([]Product, error)
	ListProductsByShop(ctx context.Context, arg ListProductsByShopParams) ([]Product, error)
	ListShopsByOrganization(ctx context.Context, arg ListShopsByOrganizationParams) ([]Shop, error)
	ListShopsByOrganizationWithStatus(ctx context.Context, arg ListShopsByOrganizationWithStatusParams) ([]Shop, error)
	ListUserOrganizations(ctx context.Context, userID uuid.UUID) ([]ListUserOrganizationsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWebhookDeliveriesByShop(ctx context.Context, arg ListWebhookDeliveriesByShopParams) ([]WebhookDelivery, error)
	ListWebhookDeliveriesByWebhook(ctx context.Context, arg ListWebhookDeliveriesByWebhookParams) ([]WebhookDelivery, error)
	ListWebhooksByOrganization(ctx context.Context, arg ListWebhooksByOrganizationParams) ([]Webhook, error)
	ListWebhooksByOrganizationAndTopic(ctx context.Context, arg ListWebhooksByOrganizationAndTopicParams) ([]Webhook, error)
	ListWebhooksByShop(ctx context.Context, arg ListWebhooksByShopParams) ([]Webhook, error)
	ListWebhooksByShopAndTopic(ctx context.Context, arg ListWebhooksByShopAndTopicParams) ([]Webhook, error)
	MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) (WebhookDelivery, error)
	MarkWebhookDeliverySuccess(ctx context.Context, arg MarkWebhookDeliverySuccessParams) (WebhookDelivery, error)
	OrganizationExistsByHandle(ctx context.Context, handle string) (bool, error)
	PublishProduct(ctx context.Context, id uuid.UUID) (Product, error)
	RemoveOrganizationMember(ctx context.Context, arg RemoveOrganizationMemberParams) error
	ResetWebhookFailureCount(ctx context.Context, id uuid.UUID) (Webhook, error)
	SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]Customer, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	SetCustomerPassword(ctx context.Context, arg SetCustomerPasswordParams) error
	SetShopCustomDomain(ctx context.Context, arg SetShopCustomDomainParams) (Shop, error)
	SetStripeCustomerID(ctx context.Context, arg SetStripeCustomerIDParams) (Organization, error)
	ShopExistsByCustomDomain(ctx context.Context, customDomain pgtype.Text) (bool, error)
	ShopExistsBySubdomain(ctx context.Context, subdomain string) (bool, error)
	SoftDeleteCustomer(ctx context.Context, id uuid.UUID) error
	SoftDeleteOrganization(ctx context.Context, id uuid.UUID) error
	SoftDeleteProduct(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UnpublishProduct(ctx context.Context, id uuid.UUID) (Product, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateCustomerStats(ctx context.Context, arg UpdateCustomerStatsParams) error
	UpdateLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateLineItemFulfillment(ctx context.Context, arg UpdateLineItemFulfillmentParams) (OrderLineItem, error)
	UpdateMarketingOptIn(ctx context.Context, arg UpdateMarketingOptInParams) (Customer, error)
	UpdateOrderRefund(ctx context.Context, arg UpdateOrderRefundParams) (Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateOrganizationMemberRole(ctx context.Context, arg UpdateOrganizationMemberRoleParams) (OrganizationMember, error)
	UpdateOrganizationPlan(ctx context.Context, arg UpdateOrganizationPlanParams) (Organization, error)
	UpdateOrganizationStatus(ctx context.Context, arg UpdateOrganizationStatusParams) (Organization, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) (Product, error)
	UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error)
	UpdateShopStatus(ctx context.Context, arg UpdateShopStatusParams) (Shop, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error)
	UpdateWebhookDelivery(ctx context.Context, arg UpdateWebhookDeliveryParams) (WebhookDelivery, error)
	UpdateWebhookStatus(ctx context.Context, arg UpdateWebhookStatusParams) (Webhook, error)
	UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) (Customer, error)
	UserExistsByEmail(ctx context.Context, email string) (bool, error)
	VerifyUserEmail(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
