// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: shops.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearShopCustomDomain = `-- name: ClearShopCustomDomain :one
UPDATE shops 
SET custom_domain = NULL, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, gid, name, handle, subdomain, custom_domain, currency, locale, timezone, shop_owner, email, phone, source, referral_code, status, created_at, updated_at, deleted_at
`

func (q *Queries) ClearShopCustomDomain(ctx context.Context, id uuid.UUID) (Shop, error) {
	row := q.db.QueryRow(ctx, clearShopCustomDomain, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Gid,
		&i.Name,
		&i.Handle,
		&i.Subdomain,
		&i.CustomDomain,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.ShopOwner,
		&i.Email,
		&i.Phone,
		&i.Source,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countShopsByOrganization = `-- name: CountShopsByOrganization :one
SELECT COUNT(*) FROM shops 
WHERE organization_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountShopsByOrganization(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countShopsByOrganization, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShop = `-- name: CreateShop :one
INSERT INTO shops (
    organization_id, 
    name, 
    handle, 
    subdomain, 
    custom_domain,
    currency, 
    locale,
    timezone, 
    shop_owner,
    email,
    phone,
    source,
    referral_code,
    status,
    gid
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, organization_id, gid, name, handle, subdomain, custom_domain, currency, locale, timezone, shop_owner, email, phone, source, referral_code, status, created_at, updated_at, deleted_at
`

type CreateShopParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Name           string      `json:"name"`
	Handle         string      `json:"handle"`
	Subdomain      string      `json:"subdomain"`
	CustomDomain   pgtype.Text `json:"custom_domain"`
	Currency       string      `json:"currency"`
	Locale         string      `json:"locale"`
	Timezone       string      `json:"timezone"`
	ShopOwner      pgtype.Text `json:"shop_owner"`
	Email          pgtype.Text `json:"email"`
	Phone          pgtype.Text `json:"phone"`
	Source         string      `json:"source"`
	ReferralCode   pgtype.Text `json:"referral_code"`
	Status         string      `json:"status"`
	Gid            pgtype.Int8 `json:"gid"`
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, createShop,
		arg.OrganizationID,
		arg.Name,
		arg.Handle,
		arg.Subdomain,
		arg.CustomDomain,
		arg.Currency,
		arg.Locale,
		arg.Timezone,
		arg.ShopOwner,
		arg.Email,
		arg.Phone,
		arg.Source,
		arg.ReferralCode,
		arg.Status,
		arg.Gid,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Gid,
		&i.Name,
		&i.Handle,
		&i.Subdomain,
		&i.CustomDomain,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.ShopOwner,
		&i.Email,
		&i.Phone,
		&i.Source,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteShop = `-- name: DeleteShop :exec
UPDATE shops 
SET deleted_at = NOW(), updated_at = NOW() 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteShop(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShop, id)
	return err
}

const getShopByCustomDomain = `-- name: GetShopByCustomDomain :one
SELECT id, organization_id, gid, name, handle, subdomain, custom_domain, currency, locale, timezone, shop_owner, email, phone, source, referral_code, status, created_at, updated_at, deleted_at FROM shops WHERE custom_domain = $1 AND deleted_at IS NULL
`

func (q *Queries) GetShopByCustomDomain(ctx context.Context, customDomain pgtype.Text) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByCustomDomain, customDomain)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Gid,
		&i.Name,
		&i.Handle,
		&i.Subdomain,
		&i.CustomDomain,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.ShopOwner,
		&i.Email,
		&i.Phone,
		&i.Source,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getShopByGID = `-- name: GetShopByGID :one
SELECT id, organization_id, gid, name, handle, subdomain, custom_domain, currency, locale, timezone, shop_owner, email, phone, source, referral_code, status, created_at, updated_at, deleted_at FROM shops WHERE gid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetShopByGID(ctx context.Context, gid pgtype.Int8) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByGID, gid)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Gid,
		&i.Name,
		&i.Handle,
		&i.Subdomain,
		&i.CustomDomain,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.ShopOwner,
		&i.Email,
		&i.Phone,
		&i.Source,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getShopByHandle = `-- name: GetShopByHandle :one
SELECT id, organization_id, gid, name, handle, subdomain, custom_domain, currency, locale, timezone, shop_owner, email, phone, source, referral_code, status, created_at, updated_at, deleted_at FROM shops 
WHERE organization_id = $1 AND handle = $2 AND deleted_at IS NULL
`

type GetShopByHandleParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Handle         string    `json:"handle"`
}

func (q *Queries) GetShopByHandle(ctx context.Context, arg GetShopByHandleParams) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByHandle, arg.OrganizationID, arg.Handle)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Gid,
		&i.Name,
		&i.Handle,
		&i.Subdomain,
		&i.CustomDomain,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.ShopOwner,
		&i.Email,
		&i.Phone,
		&i.Source,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getShopByID = `-- name: GetShopByID :one
SELECT id, organization_id, gid, name, handle, subdomain, custom_domain, currency, locale, timezone, shop_owner, email, phone, source, referral_code, status, created_at, updated_at, deleted_at FROM shops WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetShopByID(ctx context.Context, id uuid.UUID) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByID, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Gid,
		&i.Name,
		&i.Handle,
		&i.Subdomain,
		&i.CustomDomain,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.ShopOwner,
		&i.Email,
		&i.Phone,
		&i.Source,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getShopBySubdomain = `-- name: GetShopBySubdomain :one
SELECT id, organization_id, gid, name, handle, subdomain, custom_domain, currency, locale, timezone, shop_owner, email, phone, source, referral_code, status, created_at, updated_at, deleted_at FROM shops WHERE subdomain = $1 AND deleted_at IS NULL
`

func (q *Queries) GetShopBySubdomain(ctx context.Context, subdomain string) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopBySubdomain, subdomain)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Gid,
		&i.Name,
		&i.Handle,
		&i.Subdomain,
		&i.CustomDomain,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.ShopOwner,
		&i.Email,
		&i.Phone,
		&i.Source,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listShopsByOrganization = `-- name: ListShopsByOrganization :many
SELECT id, organization_id, gid, name, handle, subdomain, custom_domain, currency, locale, timezone, shop_owner, email, phone, source, referral_code, status, created_at, updated_at, deleted_at FROM shops 
WHERE organization_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListShopsByOrganizationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListShopsByOrganization(ctx context.Context, arg ListShopsByOrganizationParams) ([]Shop, error) {
	rows, err := q.db.Query(ctx, listShopsByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shop{}
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Gid,
			&i.Name,
			&i.Handle,
			&i.Subdomain,
			&i.CustomDomain,
			&i.Currency,
			&i.Locale,
			&i.Timezone,
			&i.ShopOwner,
			&i.Email,
			&i.Phone,
			&i.Source,
			&i.ReferralCode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShopsByOrganizationWithStatus = `-- name: ListShopsByOrganizationWithStatus :many
SELECT id, organization_id, gid, name, handle, subdomain, custom_domain, currency, locale, timezone, shop_owner, email, phone, source, referral_code, status, created_at, updated_at, deleted_at FROM shops 
WHERE organization_id = $1 AND status = $2 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListShopsByOrganizationWithStatusParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Status         string    `json:"status"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListShopsByOrganizationWithStatus(ctx context.Context, arg ListShopsByOrganizationWithStatusParams) ([]Shop, error) {
	rows, err := q.db.Query(ctx, listShopsByOrganizationWithStatus,
		arg.OrganizationID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shop{}
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Gid,
			&i.Name,
			&i.Handle,
			&i.Subdomain,
			&i.CustomDomain,
			&i.Currency,
			&i.Locale,
			&i.Timezone,
			&i.ShopOwner,
			&i.Email,
			&i.Phone,
			&i.Source,
			&i.ReferralCode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setShopCustomDomain = `-- name: SetShopCustomDomain :one
UPDATE shops 
SET custom_domain = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, gid, name, handle, subdomain, custom_domain, currency, locale, timezone, shop_owner, email, phone, source, referral_code, status, created_at, updated_at, deleted_at
`

type SetShopCustomDomainParams struct {
	ID           uuid.UUID   `json:"id"`
	CustomDomain pgtype.Text `json:"custom_domain"`
}

func (q *Queries) SetShopCustomDomain(ctx context.Context, arg SetShopCustomDomainParams) (Shop, error) {
	row := q.db.QueryRow(ctx, setShopCustomDomain, arg.ID, arg.CustomDomain)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Gid,
		&i.Name,
		&i.Handle,
		&i.Subdomain,
		&i.CustomDomain,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.ShopOwner,
		&i.Email,
		&i.Phone,
		&i.Source,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const shopExistsByCustomDomain = `-- name: ShopExistsByCustomDomain :one
SELECT EXISTS(SELECT 1 FROM shops WHERE custom_domain = $1 AND deleted_at IS NULL)
`

func (q *Queries) ShopExistsByCustomDomain(ctx context.Context, customDomain pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, shopExistsByCustomDomain, customDomain)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const shopExistsBySubdomain = `-- name: ShopExistsBySubdomain :one
SELECT EXISTS(SELECT 1 FROM shops WHERE subdomain = $1 AND deleted_at IS NULL)
`

func (q *Queries) ShopExistsBySubdomain(ctx context.Context, subdomain string) (bool, error) {
	row := q.db.QueryRow(ctx, shopExistsBySubdomain, subdomain)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateShop = `-- name: UpdateShop :one
UPDATE shops
SET 
    name = COALESCE($2, name),
    handle = COALESCE($3, handle),
    custom_domain = COALESCE($4, custom_domain),
    currency = COALESCE($5, currency),
    locale = COALESCE($6, locale),
    timezone = COALESCE($7, timezone),
    shop_owner = COALESCE($8, shop_owner),
    email = COALESCE($9, email),
    phone = COALESCE($10, phone),
    status = COALESCE($11, status),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, gid, name, handle, subdomain, custom_domain, currency, locale, timezone, shop_owner, email, phone, source, referral_code, status, created_at, updated_at, deleted_at
`

type UpdateShopParams struct {
	ID           uuid.UUID   `json:"id"`
	Name         pgtype.Text `json:"name"`
	Handle       pgtype.Text `json:"handle"`
	CustomDomain pgtype.Text `json:"custom_domain"`
	Currency     pgtype.Text `json:"currency"`
	Locale       pgtype.Text `json:"locale"`
	Timezone     pgtype.Text `json:"timezone"`
	ShopOwner    pgtype.Text `json:"shop_owner"`
	Email        pgtype.Text `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	Status       pgtype.Text `json:"status"`
}

func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, updateShop,
		arg.ID,
		arg.Name,
		arg.Handle,
		arg.CustomDomain,
		arg.Currency,
		arg.Locale,
		arg.Timezone,
		arg.ShopOwner,
		arg.Email,
		arg.Phone,
		arg.Status,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Gid,
		&i.Name,
		&i.Handle,
		&i.Subdomain,
		&i.CustomDomain,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.ShopOwner,
		&i.Email,
		&i.Phone,
		&i.Source,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateShopStatus = `-- name: UpdateShopStatus :one
UPDATE shops 
SET status = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, gid, name, handle, subdomain, custom_domain, currency, locale, timezone, shop_owner, email, phone, source, referral_code, status, created_at, updated_at, deleted_at
`

type UpdateShopStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateShopStatus(ctx context.Context, arg UpdateShopStatusParams) (Shop, error) {
	row := q.db.QueryRow(ctx, updateShopStatus, arg.ID, arg.Status)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Gid,
		&i.Name,
		&i.Handle,
		&i.Subdomain,
		&i.CustomDomain,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.ShopOwner,
		&i.Email,
		&i.Phone,
		&i.Source,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
