// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    email, email_verified, password_hash,
    first_name, last_name, avatar_url, phone,
    status, locale, timezone
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, email, email_verified, password_hash, first_name, last_name, avatar_url, phone, status, locale, timezone, created_at, updated_at, last_login_at, deleted_at
`

type CreateUserParams struct {
	Email         string      `json:"email"`
	EmailVerified bool        `json:"email_verified"`
	PasswordHash  pgtype.Text `json:"password_hash"`
	FirstName     pgtype.Text `json:"first_name"`
	LastName      pgtype.Text `json:"last_name"`
	AvatarUrl     pgtype.Text `json:"avatar_url"`
	Phone         pgtype.Text `json:"phone"`
	Status        string      `json:"status"`
	Locale        string      `json:"locale"`
	Timezone      string      `json:"timezone"`
}

// db/queries/users.sql
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.EmailVerified,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.Phone,
		arg.Status,
		arg.Locale,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified, password_hash, first_name, last_name, avatar_url, phone, status, locale, timezone, created_at, updated_at, last_login_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified, password_hash, first_name, last_name, avatar_url, phone, status, locale, timezone, created_at, updated_at, last_login_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, email_verified, password_hash, first_name, last_name, avatar_url, phone, status, locale, timezone, created_at, updated_at, last_login_at, deleted_at FROM users
WHERE deleted_at IS NULL
  AND ($1::TEXT IS NULL OR status = $1)
  AND ($2::TIMESTAMPTZ IS NULL OR created_at < $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListUsersParams struct {
	Status pgtype.Text        `json:"status"`
	Cursor pgtype.Timestamptz `json:"cursor"`
	Limit  int32              `json:"limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Status, arg.Cursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
			&i.Phone,
			&i.Status,
			&i.Locale,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, email_verified, password_hash, first_name, last_name, avatar_url, phone, status, locale, timezone, created_at, updated_at, last_login_at, deleted_at FROM users
WHERE deleted_at IS NULL
  AND (
    email ILIKE '%' || $1 || '%'
    OR first_name ILIKE '%' || $1 || '%'
    OR last_name ILIKE '%' || $1 || '%'
  )
ORDER BY created_at DESC
LIMIT $2
`

type SearchUsersParams struct {
	Query pgtype.Text `json:"query"`
	Limit int32       `json:"limit"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Query, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
			&i.Phone,
			&i.Status,
			&i.Locale,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    avatar_url = COALESCE($4, avatar_url),
    phone = COALESCE($5, phone),
    locale = COALESCE($6, locale),
    timezone = COALESCE($7, timezone),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, email_verified, password_hash, first_name, last_name, avatar_url, phone, status, locale, timezone, created_at, updated_at, last_login_at, deleted_at
`

type UpdateUserParams struct {
	ID        uuid.UUID   `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Phone     pgtype.Text `json:"phone"`
	Locale    pgtype.Text `json:"locale"`
	Timezone  pgtype.Text `json:"timezone"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.Phone,
		arg.Locale,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET email = $2, email_verified = FALSE, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, email_verified, password_hash, first_name, last_name, avatar_url, phone, status, locale, timezone, created_at, updated_at, last_login_at, deleted_at
`

type UpdateUserEmailParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, email_verified, password_hash, first_name, last_name, avatar_url, phone, status, locale, timezone, created_at, updated_at, last_login_at, deleted_at
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1 AND deleted_at IS NULL)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :one
UPDATE users
SET email_verified = TRUE, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, email_verified, password_hash, first_name, last_name, avatar_url, phone, status, locale, timezone, created_at, updated_at, last_login_at, deleted_at
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, verifyUserEmail, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}
