// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: webhooks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWebhooksByOrganization = `-- name: CountWebhooksByOrganization :one
SELECT COUNT(*) FROM webhooks
WHERE organization_id = $1
`

func (q *Queries) CountWebhooksByOrganization(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhooksByOrganization, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWebhooksByShop = `-- name: CountWebhooksByShop :one
SELECT COUNT(*) FROM webhooks
WHERE shop_id = $1
`

func (q *Queries) CountWebhooksByShop(ctx context.Context, shopID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhooksByShop, shopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (
    organization_id, shop_id, topic, endpoint_url, secret_hash, 
    fields, status, api_version
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, shop_id, topic, endpoint_url, secret_hash, fields, status, failure_count, last_failure_at, last_failure_reason, api_version, created_at, updated_at
`

type CreateWebhookParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	ShopID         pgtype.UUID `json:"shop_id"`
	Topic          string      `json:"topic"`
	EndpointUrl    string      `json:"endpoint_url"`
	SecretHash     string      `json:"secret_hash"`
	Fields         []string    `json:"fields"`
	Status         string      `json:"status"`
	ApiVersion     string      `json:"api_version"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.OrganizationID,
		arg.ShopID,
		arg.Topic,
		arg.EndpointUrl,
		arg.SecretHash,
		arg.Fields,
		arg.Status,
		arg.ApiVersion,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Topic,
		&i.EndpointUrl,
		&i.SecretHash,
		&i.Fields,
		&i.Status,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.LastFailureReason,
		&i.ApiVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebhook, id)
	return err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, organization_id, shop_id, topic, endpoint_url, secret_hash, fields, status, failure_count, last_failure_at, last_failure_reason, api_version, created_at, updated_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhookByID(ctx context.Context, id uuid.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Topic,
		&i.EndpointUrl,
		&i.SecretHash,
		&i.Fields,
		&i.Status,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.LastFailureReason,
		&i.ApiVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookByShopAndTopic = `-- name: GetWebhookByShopAndTopic :one
SELECT id, organization_id, shop_id, topic, endpoint_url, secret_hash, fields, status, failure_count, last_failure_at, last_failure_reason, api_version, created_at, updated_at FROM webhooks 
WHERE shop_id = $1 AND topic = $2 AND endpoint_url = $3
`

type GetWebhookByShopAndTopicParams struct {
	ShopID      pgtype.UUID `json:"shop_id"`
	Topic       string      `json:"topic"`
	EndpointUrl string      `json:"endpoint_url"`
}

func (q *Queries) GetWebhookByShopAndTopic(ctx context.Context, arg GetWebhookByShopAndTopicParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhookByShopAndTopic, arg.ShopID, arg.Topic, arg.EndpointUrl)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Topic,
		&i.EndpointUrl,
		&i.SecretHash,
		&i.Fields,
		&i.Status,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.LastFailureReason,
		&i.ApiVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementWebhookFailureCount = `-- name: IncrementWebhookFailureCount :one
UPDATE webhooks
SET 
    failure_count = failure_count + 1,
    last_failure_at = NOW(),
    last_failure_reason = $2,
    status = CASE WHEN failure_count + 1 >= 10 THEN 'disabled' ELSE status END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, shop_id, topic, endpoint_url, secret_hash, fields, status, failure_count, last_failure_at, last_failure_reason, api_version, created_at, updated_at
`

type IncrementWebhookFailureCountParams struct {
	ID                uuid.UUID   `json:"id"`
	LastFailureReason pgtype.Text `json:"last_failure_reason"`
}

func (q *Queries) IncrementWebhookFailureCount(ctx context.Context, arg IncrementWebhookFailureCountParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, incrementWebhookFailureCount, arg.ID, arg.LastFailureReason)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Topic,
		&i.EndpointUrl,
		&i.SecretHash,
		&i.Fields,
		&i.Status,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.LastFailureReason,
		&i.ApiVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhooksByOrganization = `-- name: ListWebhooksByOrganization :many
SELECT id, organization_id, shop_id, topic, endpoint_url, secret_hash, fields, status, failure_count, last_failure_at, last_failure_reason, api_version, created_at, updated_at FROM webhooks
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhooksByOrganizationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListWebhooksByOrganization(ctx context.Context, arg ListWebhooksByOrganizationParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ShopID,
			&i.Topic,
			&i.EndpointUrl,
			&i.SecretHash,
			&i.Fields,
			&i.Status,
			&i.FailureCount,
			&i.LastFailureAt,
			&i.LastFailureReason,
			&i.ApiVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByOrganizationAndTopic = `-- name: ListWebhooksByOrganizationAndTopic :many
SELECT id, organization_id, shop_id, topic, endpoint_url, secret_hash, fields, status, failure_count, last_failure_at, last_failure_reason, api_version, created_at, updated_at FROM webhooks
WHERE organization_id = $1 AND topic = $2 AND status = 'active'
ORDER BY created_at DESC
`

type ListWebhooksByOrganizationAndTopicParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Topic          string    `json:"topic"`
}

func (q *Queries) ListWebhooksByOrganizationAndTopic(ctx context.Context, arg ListWebhooksByOrganizationAndTopicParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByOrganizationAndTopic, arg.OrganizationID, arg.Topic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ShopID,
			&i.Topic,
			&i.EndpointUrl,
			&i.SecretHash,
			&i.Fields,
			&i.Status,
			&i.FailureCount,
			&i.LastFailureAt,
			&i.LastFailureReason,
			&i.ApiVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByShop = `-- name: ListWebhooksByShop :many
SELECT id, organization_id, shop_id, topic, endpoint_url, secret_hash, fields, status, failure_count, last_failure_at, last_failure_reason, api_version, created_at, updated_at FROM webhooks
WHERE shop_id = $1
  AND ($2::TEXT IS NULL OR topic = $2)
  AND ($3::TEXT IS NULL OR status = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListWebhooksByShopParams struct {
	ShopID  pgtype.UUID `json:"shop_id"`
	Column2 string      `json:"column_2"`
	Column3 string      `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListWebhooksByShop(ctx context.Context, arg ListWebhooksByShopParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByShop,
		arg.ShopID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ShopID,
			&i.Topic,
			&i.EndpointUrl,
			&i.SecretHash,
			&i.Fields,
			&i.Status,
			&i.FailureCount,
			&i.LastFailureAt,
			&i.LastFailureReason,
			&i.ApiVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByShopAndTopic = `-- name: ListWebhooksByShopAndTopic :many
SELECT id, organization_id, shop_id, topic, endpoint_url, secret_hash, fields, status, failure_count, last_failure_at, last_failure_reason, api_version, created_at, updated_at FROM webhooks
WHERE shop_id = $1 AND topic = $2 AND status = 'active'
ORDER BY created_at DESC
`

type ListWebhooksByShopAndTopicParams struct {
	ShopID pgtype.UUID `json:"shop_id"`
	Topic  string      `json:"topic"`
}

func (q *Queries) ListWebhooksByShopAndTopic(ctx context.Context, arg ListWebhooksByShopAndTopicParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByShopAndTopic, arg.ShopID, arg.Topic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ShopID,
			&i.Topic,
			&i.EndpointUrl,
			&i.SecretHash,
			&i.Fields,
			&i.Status,
			&i.FailureCount,
			&i.LastFailureAt,
			&i.LastFailureReason,
			&i.ApiVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetWebhookFailureCount = `-- name: ResetWebhookFailureCount :one
UPDATE webhooks
SET 
    failure_count = 0,
    last_failure_at = NULL,
    last_failure_reason = NULL,
    status = CASE WHEN status = 'disabled' THEN 'active' ELSE status END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, shop_id, topic, endpoint_url, secret_hash, fields, status, failure_count, last_failure_at, last_failure_reason, api_version, created_at, updated_at
`

func (q *Queries) ResetWebhookFailureCount(ctx context.Context, id uuid.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, resetWebhookFailureCount, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Topic,
		&i.EndpointUrl,
		&i.SecretHash,
		&i.Fields,
		&i.Status,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.LastFailureReason,
		&i.ApiVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks
SET 
    topic = COALESCE($2, topic),
    endpoint_url = COALESCE($3, endpoint_url),
    secret_hash = COALESCE($4, secret_hash),
    fields = COALESCE($5, fields),
    status = COALESCE($6, status),
    api_version = COALESCE($7, api_version),
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, shop_id, topic, endpoint_url, secret_hash, fields, status, failure_count, last_failure_at, last_failure_reason, api_version, created_at, updated_at
`

type UpdateWebhookParams struct {
	ID          uuid.UUID   `json:"id"`
	Topic       pgtype.Text `json:"topic"`
	EndpointUrl pgtype.Text `json:"endpoint_url"`
	SecretHash  pgtype.Text `json:"secret_hash"`
	Fields      []string    `json:"fields"`
	Status      pgtype.Text `json:"status"`
	ApiVersion  pgtype.Text `json:"api_version"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.Topic,
		arg.EndpointUrl,
		arg.SecretHash,
		arg.Fields,
		arg.Status,
		arg.ApiVersion,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Topic,
		&i.EndpointUrl,
		&i.SecretHash,
		&i.Fields,
		&i.Status,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.LastFailureReason,
		&i.ApiVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookStatus = `-- name: UpdateWebhookStatus :one
UPDATE webhooks
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, shop_id, topic, endpoint_url, secret_hash, fields, status, failure_count, last_failure_at, last_failure_reason, api_version, created_at, updated_at
`

type UpdateWebhookStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateWebhookStatus(ctx context.Context, arg UpdateWebhookStatusParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhookStatus, arg.ID, arg.Status)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Topic,
		&i.EndpointUrl,
		&i.SecretHash,
		&i.Fields,
		&i.Status,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.LastFailureReason,
		&i.ApiVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
