// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: webhook_deliveries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWebhookDeliveriesByStatus = `-- name: CountWebhookDeliveriesByStatus :one
SELECT COUNT(*) FROM webhook_deliveries 
WHERE webhook_id = $1 AND status = $2
`

type CountWebhookDeliveriesByStatusParams struct {
	WebhookID uuid.UUID `json:"webhook_id"`
	Status    string    `json:"status"`
}

func (q *Queries) CountWebhookDeliveriesByStatus(ctx context.Context, arg CountWebhookDeliveriesByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookDeliveriesByStatus, arg.WebhookID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWebhookDeliveriesByWebhook = `-- name: CountWebhookDeliveriesByWebhook :one
SELECT COUNT(*) FROM webhook_deliveries WHERE webhook_id = $1
`

func (q *Queries) CountWebhookDeliveriesByWebhook(ctx context.Context, webhookID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookDeliveriesByWebhook, webhookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (
    webhook_id, organization_id, shop_id, topic, endpoint_url,
    request_headers, request_body, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, webhook_id, organization_id, shop_id, topic, endpoint_url, request_headers, request_body, response_status, response_headers, response_body, status, attempts, next_retry_at, error_message, duration_ms, created_at, delivered_at
`

type CreateWebhookDeliveryParams struct {
	WebhookID      uuid.UUID   `json:"webhook_id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	ShopID         pgtype.UUID `json:"shop_id"`
	Topic          string      `json:"topic"`
	EndpointUrl    string      `json:"endpoint_url"`
	RequestHeaders []byte      `json:"request_headers"`
	RequestBody    []byte      `json:"request_body"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.WebhookID,
		arg.OrganizationID,
		arg.ShopID,
		arg.Topic,
		arg.EndpointUrl,
		arg.RequestHeaders,
		arg.RequestBody,
		arg.Status,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Topic,
		&i.EndpointUrl,
		&i.RequestHeaders,
		&i.RequestBody,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const deleteOldWebhookDeliveries = `-- name: DeleteOldWebhookDeliveries :exec
DELETE FROM webhook_deliveries
WHERE created_at < $1
`

func (q *Queries) DeleteOldWebhookDeliveries(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldWebhookDeliveries, createdAt)
	return err
}

const getWebhookDeliveryByID = `-- name: GetWebhookDeliveryByID :one
SELECT id, webhook_id, organization_id, shop_id, topic, endpoint_url, request_headers, request_body, response_status, response_headers, response_body, status, attempts, next_retry_at, error_message, duration_ms, created_at, delivered_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetWebhookDeliveryByID(ctx context.Context, id uuid.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDeliveryByID, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Topic,
		&i.EndpointUrl,
		&i.RequestHeaders,
		&i.RequestBody,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const listPendingWebhookDeliveries = `-- name: ListPendingWebhookDeliveries :many
SELECT id, webhook_id, organization_id, shop_id, topic, endpoint_url, request_headers, request_body, response_status, response_headers, response_body, status, attempts, next_retry_at, error_message, duration_ms, created_at, delivered_at FROM webhook_deliveries
WHERE status IN ('pending', 'retrying')
  AND (next_retry_at IS NULL OR next_retry_at <= NOW())
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingWebhookDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listPendingWebhookDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.OrganizationID,
			&i.ShopID,
			&i.Topic,
			&i.EndpointUrl,
			&i.RequestHeaders,
			&i.RequestBody,
			&i.ResponseStatus,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.Status,
			&i.Attempts,
			&i.NextRetryAt,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesByShop = `-- name: ListWebhookDeliveriesByShop :many
SELECT id, webhook_id, organization_id, shop_id, topic, endpoint_url, request_headers, request_body, response_status, response_headers, response_body, status, attempts, next_retry_at, error_message, duration_ms, created_at, delivered_at FROM webhook_deliveries
WHERE shop_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookDeliveriesByShopParams struct {
	ShopID pgtype.UUID `json:"shop_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListWebhookDeliveriesByShop(ctx context.Context, arg ListWebhookDeliveriesByShopParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByShop, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.OrganizationID,
			&i.ShopID,
			&i.Topic,
			&i.EndpointUrl,
			&i.RequestHeaders,
			&i.RequestBody,
			&i.ResponseStatus,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.Status,
			&i.Attempts,
			&i.NextRetryAt,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesByWebhook = `-- name: ListWebhookDeliveriesByWebhook :many
SELECT id, webhook_id, organization_id, shop_id, topic, endpoint_url, request_headers, request_body, response_status, response_headers, response_body, status, attempts, next_retry_at, error_message, duration_ms, created_at, delivered_at FROM webhook_deliveries
WHERE webhook_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookDeliveriesByWebhookParams struct {
	WebhookID uuid.UUID `json:"webhook_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListWebhookDeliveriesByWebhook(ctx context.Context, arg ListWebhookDeliveriesByWebhookParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByWebhook, arg.WebhookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.OrganizationID,
			&i.ShopID,
			&i.Topic,
			&i.EndpointUrl,
			&i.RequestHeaders,
			&i.RequestBody,
			&i.ResponseStatus,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.Status,
			&i.Attempts,
			&i.NextRetryAt,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDeliveryFailed = `-- name: MarkWebhookDeliveryFailed :one
UPDATE webhook_deliveries
SET 
    status = CASE WHEN attempts + 1 >= 5 THEN 'failed' ELSE 'retrying' END,
    error_message = $2,
    next_retry_at = $3,
    attempts = attempts + 1
WHERE id = $1
RETURNING id, webhook_id, organization_id, shop_id, topic, endpoint_url, request_headers, request_body, response_status, response_headers, response_body, status, attempts, next_retry_at, error_message, duration_ms, created_at, delivered_at
`

type MarkWebhookDeliveryFailedParams struct {
	ID           uuid.UUID          `json:"id"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markWebhookDeliveryFailed, arg.ID, arg.ErrorMessage, arg.NextRetryAt)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Topic,
		&i.EndpointUrl,
		&i.RequestHeaders,
		&i.RequestBody,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const markWebhookDeliverySuccess = `-- name: MarkWebhookDeliverySuccess :one
UPDATE webhook_deliveries
SET 
    status = 'success',
    response_status = $2,
    response_body = $3,
    duration_ms = $4,
    delivered_at = NOW(),
    attempts = attempts + 1
WHERE id = $1
RETURNING id, webhook_id, organization_id, shop_id, topic, endpoint_url, request_headers, request_body, response_status, response_headers, response_body, status, attempts, next_retry_at, error_message, duration_ms, created_at, delivered_at
`

type MarkWebhookDeliverySuccessParams struct {
	ID             uuid.UUID   `json:"id"`
	ResponseStatus pgtype.Int4 `json:"response_status"`
	ResponseBody   []byte      `json:"response_body"`
	DurationMs     pgtype.Int4 `json:"duration_ms"`
}

func (q *Queries) MarkWebhookDeliverySuccess(ctx context.Context, arg MarkWebhookDeliverySuccessParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markWebhookDeliverySuccess,
		arg.ID,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.DurationMs,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Topic,
		&i.EndpointUrl,
		&i.RequestHeaders,
		&i.RequestBody,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const updateWebhookDelivery = `-- name: UpdateWebhookDelivery :one
UPDATE webhook_deliveries
SET 
    response_status = COALESCE($2, response_status),
    response_headers = COALESCE($3, response_headers),
    response_body = COALESCE($4, response_body),
    status = COALESCE($5, status),
    attempts = COALESCE($6, attempts),
    next_retry_at = $7,
    error_message = $8,
    duration_ms = COALESCE($9, duration_ms),
    delivered_at = $10
WHERE id = $1
RETURNING id, webhook_id, organization_id, shop_id, topic, endpoint_url, request_headers, request_body, response_status, response_headers, response_body, status, attempts, next_retry_at, error_message, duration_ms, created_at, delivered_at
`

type UpdateWebhookDeliveryParams struct {
	ID              uuid.UUID          `json:"id"`
	ResponseStatus  pgtype.Int4        `json:"response_status"`
	ResponseHeaders []byte             `json:"response_headers"`
	ResponseBody    []byte             `json:"response_body"`
	Status          pgtype.Text        `json:"status"`
	Attempts        pgtype.Int4        `json:"attempts"`
	NextRetryAt     pgtype.Timestamptz `json:"next_retry_at"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	DurationMs      pgtype.Int4        `json:"duration_ms"`
	DeliveredAt     pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) UpdateWebhookDelivery(ctx context.Context, arg UpdateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, updateWebhookDelivery,
		arg.ID,
		arg.ResponseStatus,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.Status,
		arg.Attempts,
		arg.NextRetryAt,
		arg.ErrorMessage,
		arg.DurationMs,
		arg.DeliveredAt,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Topic,
		&i.EndpointUrl,
		&i.RequestHeaders,
		&i.RequestBody,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}
